# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\GitHub\pixelsort\pixel_sorter_gui.ui',
# licensing of 'f:\GitHub\pixelsort\pixel_sorter_gui.ui' applies.
#
# Created: Sun Sep 13 11:04:00 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 859)
        MainWindow.setMaximumSize(QtCore.QSize(1500, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.f_settings_panel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_settings_panel.sizePolicy().hasHeightForWidth())
        self.f_settings_panel.setSizePolicy(sizePolicy)
        self.f_settings_panel.setMinimumSize(QtCore.QSize(460, 460))
        self.f_settings_panel.setMaximumSize(QtCore.QSize(500, 16777215))
        self.f_settings_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f_settings_panel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f_settings_panel.setLineWidth(1)
        self.f_settings_panel.setObjectName("f_settings_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_settings_panel)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(2, 2, 0, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area_settings = QtWidgets.QScrollArea(self.f_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_settings.sizePolicy().hasHeightForWidth())
        self.scroll_area_settings.setSizePolicy(sizePolicy)
        self.scroll_area_settings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area_settings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area_settings.setWidgetResizable(True)
        self.scroll_area_settings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scroll_area_settings.setObjectName("scroll_area_settings")
        self.scroll_area_settings_content = QtWidgets.QWidget()
        self.scroll_area_settings_content.setGeometry(QtCore.QRect(0, 0, 479, 829))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_settings_content.sizePolicy().hasHeightForWidth())
        self.scroll_area_settings_content.setSizePolicy(sizePolicy)
        self.scroll_area_settings_content.setObjectName("scroll_area_settings_content")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scroll_area_settings_content)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vl_image = QtWidgets.QVBoxLayout()
        self.vl_image.setContentsMargins(2, 2, 2, 2)
        self.vl_image.setObjectName("vl_image")
        self.hl_header_image = QtWidgets.QHBoxLayout()
        self.hl_header_image.setSpacing(20)
        self.hl_header_image.setContentsMargins(-1, 0, -1, -1)
        self.hl_header_image.setObjectName("hl_header_image")
        self.t_image = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image.sizePolicy().hasHeightForWidth())
        self.t_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image.setFont(font)
        self.t_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_image.setObjectName("t_image")
        self.hl_header_image.addWidget(self.t_image)
        self.t_image_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_desc.sizePolicy().hasHeightForWidth())
        self.t_image_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_desc.setFont(font)
        self.t_image_desc.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.t_image_desc.setWordWrap(True)
        self.t_image_desc.setObjectName("t_image_desc")
        self.hl_header_image.addWidget(self.t_image_desc)
        self.vl_image.addLayout(self.hl_header_image)
        self.hl_Image = QtWidgets.QHBoxLayout()
        self.hl_Image.setContentsMargins(0, 2, 0, 2)
        self.hl_Image.setObjectName("hl_Image")
        self.vl_left = QtWidgets.QVBoxLayout()
        self.vl_left.setContentsMargins(1, 1, 1, 1)
        self.vl_left.setObjectName("vl_left")
        self.b_choose_image = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_image.sizePolicy().hasHeightForWidth())
        self.b_choose_image.setSizePolicy(sizePolicy)
        self.b_choose_image.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_image.setObjectName("b_choose_image")
        self.vl_left.addWidget(self.b_choose_image)
        self.b_load_current = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_load_current.sizePolicy().hasHeightForWidth())
        self.b_load_current.setSizePolicy(sizePolicy)
        self.b_load_current.setMinimumSize(QtCore.QSize(100, 30))
        self.b_load_current.setObjectName("b_load_current")
        self.vl_left.addWidget(self.b_load_current)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_left.addItem(spacerItem)
        self.hl_Image.addLayout(self.vl_left)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_Image.addItem(spacerItem1)
        self.vl_right = QtWidgets.QVBoxLayout()
        self.vl_right.setContentsMargins(2, 2, 2, 2)
        self.vl_right.setObjectName("vl_right")
        self.hl_Image.addLayout(self.vl_right)
        self.l_loaded_image_preview = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_loaded_image_preview.sizePolicy().hasHeightForWidth())
        self.l_loaded_image_preview.setSizePolicy(sizePolicy)
        self.l_loaded_image_preview.setMinimumSize(QtCore.QSize(75, 75))
        self.l_loaded_image_preview.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_loaded_image_preview.setFont(font)
        self.l_loaded_image_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.l_loaded_image_preview.setScaledContents(True)
        self.l_loaded_image_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loaded_image_preview.setObjectName("l_loaded_image_preview")
        self.hl_Image.addWidget(self.l_loaded_image_preview)
        self.vl_image.addLayout(self.hl_Image)
        self.verticalLayout_5.addLayout(self.vl_image)
        self.line_major_1 = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line_major_1.setWindowModality(QtCore.Qt.NonModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_major_1.sizePolicy().hasHeightForWidth())
        self.line_major_1.setSizePolicy(sizePolicy)
        self.line_major_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_major_1.setLineWidth(2)
        self.line_major_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_major_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_major_1.setObjectName("line_major_1")
        self.verticalLayout_5.addWidget(self.line_major_1)
        self.vl_image_mask = QtWidgets.QVBoxLayout()
        self.vl_image_mask.setSpacing(2)
        self.vl_image_mask.setContentsMargins(2, 2, 2, 2)
        self.vl_image_mask.setObjectName("vl_image_mask")
        self.hl_header_image_mask = QtWidgets.QHBoxLayout()
        self.hl_header_image_mask.setSpacing(20)
        self.hl_header_image_mask.setContentsMargins(0, 0, -1, -1)
        self.hl_header_image_mask.setObjectName("hl_header_image_mask")
        self.t_image_mask = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_mask.sizePolicy().hasHeightForWidth())
        self.t_image_mask.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image_mask.setFont(font)
        self.t_image_mask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_image_mask.setObjectName("t_image_mask")
        self.hl_header_image_mask.addWidget(self.t_image_mask)
        self.t_image_mask_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_mask_desc.sizePolicy().hasHeightForWidth())
        self.t_image_mask_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_mask_desc.setFont(font)
        self.t_image_mask_desc.setWordWrap(True)
        self.t_image_mask_desc.setObjectName("t_image_mask_desc")
        self.hl_header_image_mask.addWidget(self.t_image_mask_desc)
        self.vl_image_mask.addLayout(self.hl_header_image_mask)
        self.hl_mask_selection = QtWidgets.QHBoxLayout()
        self.hl_mask_selection.setObjectName("hl_mask_selection")
        self.rb_mask_none = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_none.sizePolicy().hasHeightForWidth())
        self.rb_mask_none.setSizePolicy(sizePolicy)
        self.rb_mask_none.setObjectName("rb_mask_none")
        self.hl_mask_selection.addWidget(self.rb_mask_none)
        self.rb_mask_single = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_single.sizePolicy().hasHeightForWidth())
        self.rb_mask_single.setSizePolicy(sizePolicy)
        self.rb_mask_single.setChecked(True)
        self.rb_mask_single.setObjectName("rb_mask_single")
        self.hl_mask_selection.addWidget(self.rb_mask_single)
        self.rb_mask_folder = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_folder.sizePolicy().hasHeightForWidth())
        self.rb_mask_folder.setSizePolicy(sizePolicy)
        self.rb_mask_folder.setObjectName("rb_mask_folder")
        self.hl_mask_selection.addWidget(self.rb_mask_folder)
        self.vl_image_mask.addLayout(self.hl_mask_selection)
        self.f_hl_mask_none = QtWidgets.QFrame(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_hl_mask_none.sizePolicy().hasHeightForWidth())
        self.f_hl_mask_none.setSizePolicy(sizePolicy)
        self.f_hl_mask_none.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f_hl_mask_none.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_hl_mask_none.setObjectName("f_hl_mask_none")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.f_hl_mask_none)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t_no_mask = QtWidgets.QLabel(self.f_hl_mask_none)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_no_mask.sizePolicy().hasHeightForWidth())
        self.t_no_mask.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_no_mask.setFont(font)
        self.t_no_mask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_no_mask.setObjectName("t_no_mask")
        self.horizontalLayout_11.addWidget(self.t_no_mask)
        self.vl_image_mask.addWidget(self.f_hl_mask_none)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_image_mask.addItem(spacerItem2)
        self.f_hl_mask_single = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_hl_mask_single.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f_hl_mask_single.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f_hl_mask_single.setObjectName("f_hl_mask_single")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.f_hl_mask_single)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.vl_mask_single_left = QtWidgets.QVBoxLayout()
        self.vl_mask_single_left.setContentsMargins(0, 0, 0, 0)
        self.vl_mask_single_left.setObjectName("vl_mask_single_left")
        self.b_choose_mask = QtWidgets.QPushButton(self.f_hl_mask_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_mask.sizePolicy().hasHeightForWidth())
        self.b_choose_mask.setSizePolicy(sizePolicy)
        self.b_choose_mask.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_mask.setObjectName("b_choose_mask")
        self.vl_mask_single_left.addWidget(self.b_choose_mask)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_mask_single_left.addItem(spacerItem3)
        self.horizontalLayout_12.addLayout(self.vl_mask_single_left)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.vl_mask_single_right = QtWidgets.QVBoxLayout()
        self.vl_mask_single_right.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_single_right.setObjectName("vl_mask_single_right")
        self.horizontalLayout_12.addLayout(self.vl_mask_single_right)
        self.l_loaded_mask_preview = QtWidgets.QLabel(self.f_hl_mask_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_loaded_mask_preview.sizePolicy().hasHeightForWidth())
        self.l_loaded_mask_preview.setSizePolicy(sizePolicy)
        self.l_loaded_mask_preview.setMinimumSize(QtCore.QSize(75, 75))
        self.l_loaded_mask_preview.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_loaded_mask_preview.setFont(font)
        self.l_loaded_mask_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.l_loaded_mask_preview.setScaledContents(True)
        self.l_loaded_mask_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loaded_mask_preview.setObjectName("l_loaded_mask_preview")
        self.horizontalLayout_12.addWidget(self.l_loaded_mask_preview)
        self.vl_image_mask.addWidget(self.f_hl_mask_single)
        self.f_vl_mask_folder = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_vl_mask_folder.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f_vl_mask_folder.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_vl_mask_folder.setObjectName("f_vl_mask_folder")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_vl_mask_folder)
        self.verticalLayout_3.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.t_mask_folder_info_header = QtWidgets.QLabel(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_mask_folder_info_header.sizePolicy().hasHeightForWidth())
        self.t_mask_folder_info_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_mask_folder_info_header.setFont(font)
        self.t_mask_folder_info_header.setWordWrap(True)
        self.t_mask_folder_info_header.setObjectName("t_mask_folder_info_header")
        self.verticalLayout_3.addWidget(self.t_mask_folder_info_header)
        self.hl_mask_folder = QtWidgets.QHBoxLayout()
        self.hl_mask_folder.setContentsMargins(2, 2, 2, 2)
        self.hl_mask_folder.setObjectName("hl_mask_folder")
        self.vl_mask_folder_left = QtWidgets.QVBoxLayout()
        self.vl_mask_folder_left.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_folder_left.setObjectName("vl_mask_folder_left")
        self.b_choose_mask_folder = QtWidgets.QPushButton(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_mask_folder.sizePolicy().hasHeightForWidth())
        self.b_choose_mask_folder.setSizePolicy(sizePolicy)
        self.b_choose_mask_folder.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_mask_folder.setObjectName("b_choose_mask_folder")
        self.vl_mask_folder_left.addWidget(self.b_choose_mask_folder)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_mask_folder_left.addItem(spacerItem5)
        self.hl_mask_folder.addLayout(self.vl_mask_folder_left)
        self.vl_mask_folder_right = QtWidgets.QVBoxLayout()
        self.vl_mask_folder_right.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_folder_right.setObjectName("vl_mask_folder_right")
        self.t_found_masks = QtWidgets.QLabel(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_found_masks.sizePolicy().hasHeightForWidth())
        self.t_found_masks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.t_found_masks.setFont(font)
        self.t_found_masks.setObjectName("t_found_masks")
        self.vl_mask_folder_right.addWidget(self.t_found_masks)
        self.scrollArea = QtWidgets.QScrollArea(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_area_found_masks = QtWidgets.QWidget()
        self.scroll_area_found_masks.setGeometry(QtCore.QRect(0, 0, 335, 69))
        self.scroll_area_found_masks.setObjectName("scroll_area_found_masks")
        self.gridLayout = QtWidgets.QGridLayout(self.scroll_area_found_masks)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vl_found_masks = QtWidgets.QVBoxLayout()
        self.vl_found_masks.setSpacing(2)
        self.vl_found_masks.setObjectName("vl_found_masks")
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_found_masks.addItem(spacerItem6)
        self.gridLayout.addLayout(self.vl_found_masks, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scroll_area_found_masks)
        self.vl_mask_folder_right.addWidget(self.scrollArea)
        self.hl_mask_folder.addLayout(self.vl_mask_folder_right)
        self.verticalLayout_3.addLayout(self.hl_mask_folder)
        self.vl_image_mask.addWidget(self.f_vl_mask_folder)
        self.verticalLayout_5.addLayout(self.vl_image_mask)
        self.line_major_2 = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line_major_2.setWindowModality(QtCore.Qt.NonModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_major_2.sizePolicy().hasHeightForWidth())
        self.line_major_2.setSizePolicy(sizePolicy)
        self.line_major_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_major_2.setLineWidth(2)
        self.line_major_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_major_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_major_2.setObjectName("line_major_2")
        self.verticalLayout_5.addWidget(self.line_major_2)
        self.vl_interval_function = QtWidgets.QVBoxLayout()
        self.vl_interval_function.setContentsMargins(2, 2, 2, 2)
        self.vl_interval_function.setObjectName("vl_interval_function")
        self.hl_header_interval_sorting = QtWidgets.QHBoxLayout()
        self.hl_header_interval_sorting.setSpacing(20)
        self.hl_header_interval_sorting.setContentsMargins(-1, 0, -1, -1)
        self.hl_header_interval_sorting.setObjectName("hl_header_interval_sorting")
        self.t_interval_sorting = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_interval_sorting.sizePolicy().hasHeightForWidth())
        self.t_interval_sorting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_interval_sorting.setFont(font)
        self.t_interval_sorting.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_interval_sorting.setObjectName("t_interval_sorting")
        self.hl_header_interval_sorting.addWidget(self.t_interval_sorting)
        self.t_interval_sorting_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_interval_sorting_desc.sizePolicy().hasHeightForWidth())
        self.t_interval_sorting_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_interval_sorting_desc.setFont(font)
        self.t_interval_sorting_desc.setObjectName("t_interval_sorting_desc")
        self.hl_header_interval_sorting.addWidget(self.t_interval_sorting_desc)
        self.vl_interval_function.addLayout(self.hl_header_interval_sorting)
        self.hl_interval_function = QtWidgets.QHBoxLayout()
        self.hl_interval_function.setSpacing(20)
        self.hl_interval_function.setContentsMargins(-1, 0, -1, -1)
        self.hl_interval_function.setObjectName("hl_interval_function")
        self.cb_interval_function = QtWidgets.QComboBox(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_interval_function.sizePolicy().hasHeightForWidth())
        self.cb_interval_function.setSizePolicy(sizePolicy)
        self.cb_interval_function.setMinimumSize(QtCore.QSize(90, 0))
        self.cb_interval_function.setEditable(False)
        self.cb_interval_function.setFrame(True)
        self.cb_interval_function.setObjectName("cb_interval_function")
        self.hl_interval_function.addWidget(self.cb_interval_function)
        self.t_interval_function_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_interval_function_desc.setFont(font)
        self.t_interval_function_desc.setWordWrap(True)
        self.t_interval_function_desc.setObjectName("t_interval_function_desc")
        self.hl_interval_function.addWidget(self.t_interval_function_desc)
        self.vl_interval_function.addLayout(self.hl_interval_function)
        self.hl_parameters_indent = QtWidgets.QHBoxLayout()
        self.hl_parameters_indent.setContentsMargins(0, 2, 0, 2)
        self.hl_parameters_indent.setObjectName("hl_parameters_indent")
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hl_parameters_indent.addItem(spacerItem7)
        self.line_3 = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.hl_parameters_indent.addWidget(self.line_3)
        self.vl_parameters_shell = QtWidgets.QVBoxLayout()
        self.vl_parameters_shell.setSpacing(2)
        self.vl_parameters_shell.setObjectName("vl_parameters_shell")
        self.line = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vl_parameters_shell.addWidget(self.line)
        self.hl_parameters_subtitle = QtWidgets.QHBoxLayout()
        self.hl_parameters_subtitle.setObjectName("hl_parameters_subtitle")
        self.t_parameters_subtitle = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_parameters_subtitle.sizePolicy().hasHeightForWidth())
        self.t_parameters_subtitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(False)
        self.t_parameters_subtitle.setFont(font)
        self.t_parameters_subtitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_parameters_subtitle.setObjectName("t_parameters_subtitle")
        self.hl_parameters_subtitle.addWidget(self.t_parameters_subtitle)
        self.b_load_current_2 = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_load_current_2.sizePolicy().hasHeightForWidth())
        self.b_load_current_2.setSizePolicy(sizePolicy)
        self.b_load_current_2.setMinimumSize(QtCore.QSize(100, 30))
        self.b_load_current_2.setObjectName("b_load_current_2")
        self.hl_parameters_subtitle.addWidget(self.b_load_current_2)
        self.vl_parameters_shell.addLayout(self.hl_parameters_subtitle)
        self.vl_parameters = QtWidgets.QVBoxLayout()
        self.vl_parameters.setContentsMargins(0, 2, 0, 2)
        self.vl_parameters.setObjectName("vl_parameters")
        self.vl_parameters_shell.addLayout(self.vl_parameters)
        self.hl_parameters_indent.addLayout(self.vl_parameters_shell)
        self.vl_interval_function.addLayout(self.hl_parameters_indent)
        spacerItem8 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.vl_interval_function.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.vl_interval_function)
        self.line_major_3 = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line_major_3.setWindowModality(QtCore.Qt.NonModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_major_3.sizePolicy().hasHeightForWidth())
        self.line_major_3.setSizePolicy(sizePolicy)
        self.line_major_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_major_3.setLineWidth(2)
        self.line_major_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_major_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_major_3.setObjectName("line_major_3")
        self.verticalLayout_5.addWidget(self.line_major_3)
        self.vl_pixel_ordering = QtWidgets.QVBoxLayout()
        self.vl_pixel_ordering.setContentsMargins(2, 2, 2, 2)
        self.vl_pixel_ordering.setObjectName("vl_pixel_ordering")
        self.hl_header_pixel_ordering = QtWidgets.QHBoxLayout()
        self.hl_header_pixel_ordering.setSpacing(20)
        self.hl_header_pixel_ordering.setObjectName("hl_header_pixel_ordering")
        self.t_pixel_ordering = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_pixel_ordering.setFont(font)
        self.t_pixel_ordering.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_pixel_ordering.setObjectName("t_pixel_ordering")
        self.hl_header_pixel_ordering.addWidget(self.t_pixel_ordering)
        self.t_pixel_ordering_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering_desc.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_pixel_ordering_desc.setFont(font)
        self.t_pixel_ordering_desc.setWordWrap(True)
        self.t_pixel_ordering_desc.setObjectName("t_pixel_ordering_desc")
        self.hl_header_pixel_ordering.addWidget(self.t_pixel_ordering_desc)
        self.vl_pixel_ordering.addLayout(self.hl_header_pixel_ordering)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cb_pixel_ordering_option = QtWidgets.QComboBox(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_pixel_ordering_option.sizePolicy().hasHeightForWidth())
        self.cb_pixel_ordering_option.setSizePolicy(sizePolicy)
        self.cb_pixel_ordering_option.setMinimumSize(QtCore.QSize(80, 0))
        self.cb_pixel_ordering_option.setEditable(False)
        self.cb_pixel_ordering_option.setFrame(True)
        self.cb_pixel_ordering_option.setObjectName("cb_pixel_ordering_option")
        self.horizontalLayout_6.addWidget(self.cb_pixel_ordering_option)
        self.t_pixel_ordering_option_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering_option_desc.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering_option_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_pixel_ordering_option_desc.setFont(font)
        self.t_pixel_ordering_option_desc.setWordWrap(True)
        self.t_pixel_ordering_option_desc.setObjectName("t_pixel_ordering_option_desc")
        self.horizontalLayout_6.addWidget(self.t_pixel_ordering_option_desc)
        self.vl_pixel_ordering.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.vl_pixel_ordering)
        self.line_major_4 = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line_major_4.setWindowModality(QtCore.Qt.NonModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_major_4.sizePolicy().hasHeightForWidth())
        self.line_major_4.setSizePolicy(sizePolicy)
        self.line_major_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_major_4.setLineWidth(2)
        self.line_major_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_major_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_major_4.setObjectName("line_major_4")
        self.verticalLayout_5.addWidget(self.line_major_4)
        self.vl_save_location = QtWidgets.QVBoxLayout()
        self.vl_save_location.setContentsMargins(2, 2, 2, 2)
        self.vl_save_location.setObjectName("vl_save_location")
        self.hl_header_image_output = QtWidgets.QHBoxLayout()
        self.hl_header_image_output.setSpacing(20)
        self.hl_header_image_output.setObjectName("hl_header_image_output")
        self.t_image_output = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_output.sizePolicy().hasHeightForWidth())
        self.t_image_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image_output.setFont(font)
        self.t_image_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_image_output.setObjectName("t_image_output")
        self.hl_header_image_output.addWidget(self.t_image_output)
        self.t_save_location_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location_desc.sizePolicy().hasHeightForWidth())
        self.t_save_location_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_desc.setFont(font)
        self.t_save_location_desc.setWordWrap(True)
        self.t_save_location_desc.setObjectName("t_save_location_desc")
        self.hl_header_image_output.addWidget(self.t_save_location_desc)
        self.vl_save_location.addLayout(self.hl_header_image_output)
        self.vl_generation = QtWidgets.QVBoxLayout()
        self.vl_generation.setContentsMargins(2, 2, 2, 2)
        self.vl_generation.setObjectName("vl_generation")
        self.hl_generation_2 = QtWidgets.QHBoxLayout()
        self.hl_generation_2.setObjectName("hl_generation_2")
        self.vl_sort_options = QtWidgets.QVBoxLayout()
        self.vl_sort_options.setObjectName("vl_sort_options")
        self.t_sort_image_title = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.t_sort_image_title.setFont(font)
        self.t_sort_image_title.setObjectName("t_sort_image_title")
        self.vl_sort_options.addWidget(self.t_sort_image_title)
        self.cb_sort_option_preview = QtWidgets.QCheckBox(self.scroll_area_settings_content)
        self.cb_sort_option_preview.setObjectName("cb_sort_option_preview")
        self.vl_sort_options.addWidget(self.cb_sort_option_preview)
        spacerItem9 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_sort_options.addItem(spacerItem9)
        self.hl_generation_2.addLayout(self.vl_sort_options)
        self.vl_post_sort_options = QtWidgets.QVBoxLayout()
        self.vl_post_sort_options.setObjectName("vl_post_sort_options")
        self.t_post_sort_after_image_sort = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.t_post_sort_after_image_sort.setFont(font)
        self.t_post_sort_after_image_sort.setObjectName("t_post_sort_after_image_sort")
        self.vl_post_sort_options.addWidget(self.t_post_sort_after_image_sort)
        self.cb_post_sort_option_save_on_create = QtWidgets.QCheckBox(self.scroll_area_settings_content)
        self.cb_post_sort_option_save_on_create.setObjectName("cb_post_sort_option_save_on_create")
        self.vl_post_sort_options.addWidget(self.cb_post_sort_option_save_on_create)
        self.cb_post_sort_option_picture_viewer = QtWidgets.QCheckBox(self.scroll_area_settings_content)
        self.cb_post_sort_option_picture_viewer.setObjectName("cb_post_sort_option_picture_viewer")
        self.vl_post_sort_options.addWidget(self.cb_post_sort_option_picture_viewer)
        self.hl_generation_2.addLayout(self.vl_post_sort_options)
        self.vl_generation.addLayout(self.hl_generation_2)
        self.hl_generation = QtWidgets.QHBoxLayout()
        self.hl_generation.setSpacing(6)
        self.hl_generation.setObjectName("hl_generation")
        self.b_generate_pixel_sort = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_generate_pixel_sort.sizePolicy().hasHeightForWidth())
        self.b_generate_pixel_sort.setSizePolicy(sizePolicy)
        self.b_generate_pixel_sort.setMinimumSize(QtCore.QSize(100, 30))
        self.b_generate_pixel_sort.setObjectName("b_generate_pixel_sort")
        self.hl_generation.addWidget(self.b_generate_pixel_sort)
        spacerItem10 = QtWidgets.QSpacerItem(8, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hl_generation.addItem(spacerItem10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.t_image_size_note = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_size_note.sizePolicy().hasHeightForWidth())
        self.t_image_size_note.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_size_note.setFont(font)
        self.t_image_size_note.setWordWrap(True)
        self.t_image_size_note.setObjectName("t_image_size_note")
        self.verticalLayout_6.addWidget(self.t_image_size_note)
        self.t_image_size_warning_dynamic = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_size_warning_dynamic.sizePolicy().hasHeightForWidth())
        self.t_image_size_warning_dynamic.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.t_image_size_warning_dynamic.setPalette(palette)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_size_warning_dynamic.setFont(font)
        self.t_image_size_warning_dynamic.setWordWrap(True)
        self.t_image_size_warning_dynamic.setObjectName("t_image_size_warning_dynamic")
        self.verticalLayout_6.addWidget(self.t_image_size_warning_dynamic)
        self.hl_generation.addLayout(self.verticalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.hl_generation.addItem(spacerItem11)
        self.vl_generation.addLayout(self.hl_generation)
        self.hl_save_location = QtWidgets.QHBoxLayout()
        self.hl_save_location.setSpacing(2)
        self.hl_save_location.setObjectName("hl_save_location")
        self.b_save_image = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save_image.sizePolicy().hasHeightForWidth())
        self.b_save_image.setSizePolicy(sizePolicy)
        self.b_save_image.setMinimumSize(QtCore.QSize(100, 30))
        self.b_save_image.setObjectName("b_save_image")
        self.hl_save_location.addWidget(self.b_save_image)
        spacerItem12 = QtWidgets.QSpacerItem(16, 13, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hl_save_location.addItem(spacerItem12)
        self.t_save_location_current_static = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location_current_static.sizePolicy().hasHeightForWidth())
        self.t_save_location_current_static.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_current_static.setFont(font)
        self.t_save_location_current_static.setWordWrap(True)
        self.t_save_location_current_static.setObjectName("t_save_location_current_static")
        self.hl_save_location.addWidget(self.t_save_location_current_static)
        self.t_save_location_current = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location_current.sizePolicy().hasHeightForWidth())
        self.t_save_location_current.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_current.setFont(font)
        self.t_save_location_current.setWordWrap(True)
        self.t_save_location_current.setObjectName("t_save_location_current")
        self.hl_save_location.addWidget(self.t_save_location_current)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.hl_save_location.addItem(spacerItem13)
        self.b_choose_save_location = QtWidgets.QToolButton(self.scroll_area_settings_content)
        self.b_choose_save_location.setObjectName("b_choose_save_location")
        self.hl_save_location.addWidget(self.b_choose_save_location)
        self.vl_generation.addLayout(self.hl_save_location)
        self.vl_save_location.addLayout(self.vl_generation)
        spacerItem14 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_save_location.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.vl_save_location)
        spacerItem15 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.scroll_area_settings.setWidget(self.scroll_area_settings_content)
        self.verticalLayout.addWidget(self.scroll_area_settings)
        self.horizontalLayout.addWidget(self.f_settings_panel)
        self.f_preview_panel = QtWidgets.QFrame(self.centralwidget)
        self.f_preview_panel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_preview_panel.sizePolicy().hasHeightForWidth())
        self.f_preview_panel.setSizePolicy(sizePolicy)
        self.f_preview_panel.setAutoFillBackground(False)
        self.f_preview_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f_preview_panel.setObjectName("f_preview_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_preview_panel)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl_image_preview_top = QtWidgets.QHBoxLayout()
        self.hl_image_preview_top.setObjectName("hl_image_preview_top")
        self.cb_live_preview = QtWidgets.QCheckBox(self.f_preview_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_live_preview.sizePolicy().hasHeightForWidth())
        self.cb_live_preview.setSizePolicy(sizePolicy)
        self.cb_live_preview.setObjectName("cb_live_preview")
        self.hl_image_preview_top.addWidget(self.cb_live_preview)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.t_image_preview_orig_name_dyn = QtWidgets.QLabel(self.f_preview_panel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_preview_orig_name_dyn.setFont(font)
        self.t_image_preview_orig_name_dyn.setObjectName("t_image_preview_orig_name_dyn")
        self.verticalLayout_7.addWidget(self.t_image_preview_orig_name_dyn)
        self.t_image_preview_sizes_dyn = QtWidgets.QLabel(self.f_preview_panel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_preview_sizes_dyn.setFont(font)
        self.t_image_preview_sizes_dyn.setObjectName("t_image_preview_sizes_dyn")
        self.verticalLayout_7.addWidget(self.t_image_preview_sizes_dyn)
        self.t_image_preview_ratio_dyn = QtWidgets.QLabel(self.f_preview_panel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_preview_ratio_dyn.setFont(font)
        self.t_image_preview_ratio_dyn.setObjectName("t_image_preview_ratio_dyn")
        self.verticalLayout_7.addWidget(self.t_image_preview_ratio_dyn)
        self.hl_image_preview_top.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.hl_image_preview_top)
        self.line_2 = QtWidgets.QFrame(self.f_preview_panel)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.hl_image_preview = QtWidgets.QHBoxLayout()
        self.hl_image_preview.setContentsMargins(0, 0, 0, 0)
        self.hl_image_preview.setObjectName("hl_image_preview")
        self.l_generated_image = QtWidgets.QLabel(self.f_preview_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_generated_image.sizePolicy().hasHeightForWidth())
        self.l_generated_image.setSizePolicy(sizePolicy)
        self.l_generated_image.setMinimumSize(QtCore.QSize(200, 200))
        self.l_generated_image.setMaximumSize(QtCore.QSize(1000, 900))
        self.l_generated_image.setText("")
        self.l_generated_image.setScaledContents(True)
        self.l_generated_image.setAlignment(QtCore.Qt.AlignCenter)
        self.l_generated_image.setObjectName("l_generated_image")
        self.hl_image_preview.addWidget(self.l_generated_image)
        spacerItem16 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.hl_image_preview.addItem(spacerItem16)
        self.verticalLayout_2.addLayout(self.hl_image_preview)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(1, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem18)
        self.hl_image_preview_bottom = QtWidgets.QHBoxLayout()
        self.hl_image_preview_bottom.setObjectName("hl_image_preview_bottom")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_image_preview_bottom.addItem(spacerItem19)
        self.b_open_in_native_viewer = QtWidgets.QPushButton(self.f_preview_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_open_in_native_viewer.sizePolicy().hasHeightForWidth())
        self.b_open_in_native_viewer.setSizePolicy(sizePolicy)
        self.b_open_in_native_viewer.setMinimumSize(QtCore.QSize(100, 30))
        self.b_open_in_native_viewer.setObjectName("b_open_in_native_viewer")
        self.hl_image_preview_bottom.addWidget(self.b_open_in_native_viewer)
        self.verticalLayout_2.addLayout(self.hl_image_preview_bottom)
        self.horizontalLayout.addWidget(self.f_preview_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhi = QtWidgets.QAction(MainWindow)
        self.actionhi.setObjectName("actionhi")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.t_image.setText(QtWidgets.QApplication.translate("MainWindow", "Image", None, -1))
        self.t_image_desc.setText(QtWidgets.QApplication.translate("MainWindow", "*Required* This is the image that will have pixel sorting applied to it. JPG, PNG, TIFF, etc.", None, -1))
        self.b_choose_image.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Image", None, -1))
        self.b_load_current.setText(QtWidgets.QApplication.translate("MainWindow", "Load Current", None, -1))
        self.l_loaded_image_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Loaded image will display here", None, -1))
        self.t_image_mask.setText(QtWidgets.QApplication.translate("MainWindow", "Image Mask", None, -1))
        self.t_image_mask_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Image used for masking parts of the image. Must be black and white.", None, -1))
        self.rb_mask_none.setText(QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.rb_mask_single.setText(QtWidgets.QApplication.translate("MainWindow", "Single Mask", None, -1))
        self.rb_mask_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Masks from Folder", None, -1))
        self.t_no_mask.setText(QtWidgets.QApplication.translate("MainWindow", "No mask image will be used.", None, -1))
        self.b_choose_mask.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Image", None, -1))
        self.l_loaded_mask_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Loaded mask will display here", None, -1))
        self.t_mask_folder_info_header.setText(QtWidgets.QApplication.translate("MainWindow", "Note: If the loaded image is in found in the mask folder it will be ignored.", None, -1))
        self.b_choose_mask_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Folder", None, -1))
        self.t_found_masks.setText(QtWidgets.QApplication.translate("MainWindow", "Found Masks:", None, -1))
        self.t_interval_sorting.setText(QtWidgets.QApplication.translate("MainWindow", "Interval Sorting", None, -1))
        self.t_interval_sorting_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Controls how the intervals used for sorting are defined.", None, -1))
        self.t_interval_function_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.t_parameters_subtitle.setText(QtWidgets.QApplication.translate("MainWindow", "Parameters:", None, -1))
        self.b_load_current_2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Save the current settings as the default for next time.", None, -1))
        self.b_load_current_2.setText(QtWidgets.QApplication.translate("MainWindow", "Save as Default", None, -1))
        self.t_pixel_ordering.setText(QtWidgets.QApplication.translate("MainWindow", "Pixel Ordering", None, -1))
        self.t_pixel_ordering_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Way in which the pixels are ordered.", None, -1))
        self.t_pixel_ordering_option_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.t_image_output.setText(QtWidgets.QApplication.translate("MainWindow", "Image Output", None, -1))
        self.t_save_location_desc.setText(QtWidgets.QApplication.translate("MainWindow", "The fun part!", None, -1))
        self.t_sort_image_title.setText(QtWidgets.QApplication.translate("MainWindow", "Image Settings", None, -1))
        self.cb_sort_option_preview.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Will save files as soon as they are created", None, -1))
        self.cb_sort_option_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Preview Mode (1000px image)", None, -1))
        self.t_post_sort_after_image_sort.setText(QtWidgets.QApplication.translate("MainWindow", "After image(s) are sorted:", None, -1))
        self.cb_post_sort_option_save_on_create.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Will save files as soon as they are created", None, -1))
        self.cb_post_sort_option_save_on_create.setText(QtWidgets.QApplication.translate("MainWindow", "Save image(s)", None, -1))
        self.cb_post_sort_option_picture_viewer.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Will save files as soon as they are created", None, -1))
        self.cb_post_sort_option_picture_viewer.setText(QtWidgets.QApplication.translate("MainWindow", "Open in native picture viewer", None, -1))
        self.b_generate_pixel_sort.setText(QtWidgets.QApplication.translate("MainWindow", "Pixel Sort!", None, -1))
        self.t_image_size_note.setText(QtWidgets.QApplication.translate("MainWindow", "Note: Depending on the size of the image this could take a few seconds to several minutes.", None, -1))
        self.t_image_size_warning_dynamic.setText(QtWidgets.QApplication.translate("MainWindow", "(image size warning)", None, -1))
        self.b_save_image.setText(QtWidgets.QApplication.translate("MainWindow", "Save Sorted Image", None, -1))
        self.t_save_location_current_static.setText(QtWidgets.QApplication.translate("MainWindow", "Current Folder: ", None, -1))
        self.t_save_location_current.setText(QtWidgets.QApplication.translate("MainWindow", "(save location)", None, -1))
        self.b_choose_save_location.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.cb_live_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Live Preview", None, -1))
        self.t_image_preview_orig_name_dyn.setText(QtWidgets.QApplication.translate("MainWindow", "(image name)", None, -1))
        self.t_image_preview_sizes_dyn.setText(QtWidgets.QApplication.translate("MainWindow", "(image size)", None, -1))
        self.t_image_preview_ratio_dyn.setText(QtWidgets.QApplication.translate("MainWindow", "(image ratio)", None, -1))
        self.b_open_in_native_viewer.setText(QtWidgets.QApplication.translate("MainWindow", "Open in Viewer", None, -1))
        self.actionhi.setText(QtWidgets.QApplication.translate("MainWindow", "hi", None, -1))

