# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\GitHub\pixelsort\pixel_sorter_gui.ui',
# licensing of 'f:\GitHub\pixelsort\pixel_sorter_gui.ui' applies.
#
# Created: Mon Sep  7 12:56:41 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1399, 1000)
        MainWindow.setMaximumSize(QtCore.QSize(1500, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.f_settings_panel = QtWidgets.QFrame(self.centralwidget)
        self.f_settings_panel.setMaximumSize(QtCore.QSize(600, 16777215))
        self.f_settings_panel.setFrameShape(QtWidgets.QFrame.Panel)
        self.f_settings_panel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_settings_panel.setLineWidth(1)
        self.f_settings_panel.setObjectName("f_settings_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_settings_panel)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(2, 2, 0, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area_settings = QtWidgets.QScrollArea(self.f_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_settings.sizePolicy().hasHeightForWidth())
        self.scroll_area_settings.setSizePolicy(sizePolicy)
        self.scroll_area_settings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area_settings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area_settings.setWidgetResizable(True)
        self.scroll_area_settings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scroll_area_settings.setObjectName("scroll_area_settings")
        self.scroll_area_settings_content = QtWidgets.QWidget()
        self.scroll_area_settings_content.setGeometry(QtCore.QRect(0, 0, 402, 1065))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_settings_content.sizePolicy().hasHeightForWidth())
        self.scroll_area_settings_content.setSizePolicy(sizePolicy)
        self.scroll_area_settings_content.setObjectName("scroll_area_settings_content")
        self.gridLayout = QtWidgets.QGridLayout(self.scroll_area_settings_content)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vl_image_mask = QtWidgets.QVBoxLayout()
        self.vl_image_mask.setSpacing(2)
        self.vl_image_mask.setContentsMargins(2, 2, 2, 2)
        self.vl_image_mask.setObjectName("vl_image_mask")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.t_image_mask = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_mask.sizePolicy().hasHeightForWidth())
        self.t_image_mask.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image_mask.setFont(font)
        self.t_image_mask.setObjectName("t_image_mask")
        self.horizontalLayout_8.addWidget(self.t_image_mask)
        self.t_image_mask_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_mask_desc.setFont(font)
        self.t_image_mask_desc.setObjectName("t_image_mask_desc")
        self.horizontalLayout_8.addWidget(self.t_image_mask_desc)
        self.vl_image_mask.addLayout(self.horizontalLayout_8)
        self.hl_mask_selection = QtWidgets.QHBoxLayout()
        self.hl_mask_selection.setObjectName("hl_mask_selection")
        self.rb_mask_none = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_none.sizePolicy().hasHeightForWidth())
        self.rb_mask_none.setSizePolicy(sizePolicy)
        self.rb_mask_none.setObjectName("rb_mask_none")
        self.hl_mask_selection.addWidget(self.rb_mask_none)
        self.rb_mask_single = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_single.sizePolicy().hasHeightForWidth())
        self.rb_mask_single.setSizePolicy(sizePolicy)
        self.rb_mask_single.setChecked(True)
        self.rb_mask_single.setObjectName("rb_mask_single")
        self.hl_mask_selection.addWidget(self.rb_mask_single)
        self.rb_mask_folder = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_folder.sizePolicy().hasHeightForWidth())
        self.rb_mask_folder.setSizePolicy(sizePolicy)
        self.rb_mask_folder.setObjectName("rb_mask_folder")
        self.hl_mask_selection.addWidget(self.rb_mask_folder)
        self.vl_image_mask.addLayout(self.hl_mask_selection)
        self.f_hl_mask_none = QtWidgets.QFrame(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_hl_mask_none.sizePolicy().hasHeightForWidth())
        self.f_hl_mask_none.setSizePolicy(sizePolicy)
        self.f_hl_mask_none.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_hl_mask_none.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_hl_mask_none.setObjectName("f_hl_mask_none")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.f_hl_mask_none)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t_no_mask = QtWidgets.QLabel(self.f_hl_mask_none)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_no_mask.sizePolicy().hasHeightForWidth())
        self.t_no_mask.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_no_mask.setFont(font)
        self.t_no_mask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_no_mask.setObjectName("t_no_mask")
        self.horizontalLayout_11.addWidget(self.t_no_mask)
        self.vl_image_mask.addWidget(self.f_hl_mask_none)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_image_mask.addItem(spacerItem)
        self.f_hl_mask_single = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_hl_mask_single.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_hl_mask_single.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_hl_mask_single.setObjectName("f_hl_mask_single")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.f_hl_mask_single)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.vl_mask_single_left = QtWidgets.QVBoxLayout()
        self.vl_mask_single_left.setContentsMargins(1, 1, 1, 1)
        self.vl_mask_single_left.setObjectName("vl_mask_single_left")
        self.b_choose_mask = QtWidgets.QPushButton(self.f_hl_mask_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_mask.sizePolicy().hasHeightForWidth())
        self.b_choose_mask.setSizePolicy(sizePolicy)
        self.b_choose_mask.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_mask.setObjectName("b_choose_mask")
        self.vl_mask_single_left.addWidget(self.b_choose_mask)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_mask_single_left.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.vl_mask_single_left)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.vl_mask_single_right = QtWidgets.QVBoxLayout()
        self.vl_mask_single_right.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_single_right.setObjectName("vl_mask_single_right")
        self.l_loaded_mask_preview = QtWidgets.QLabel(self.f_hl_mask_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_loaded_mask_preview.sizePolicy().hasHeightForWidth())
        self.l_loaded_mask_preview.setSizePolicy(sizePolicy)
        self.l_loaded_mask_preview.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_loaded_mask_preview.setFont(font)
        self.l_loaded_mask_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.l_loaded_mask_preview.setScaledContents(True)
        self.l_loaded_mask_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loaded_mask_preview.setObjectName("l_loaded_mask_preview")
        self.vl_mask_single_right.addWidget(self.l_loaded_mask_preview)
        self.horizontalLayout_12.addLayout(self.vl_mask_single_right)
        self.vl_image_mask.addWidget(self.f_hl_mask_single)
        self.f_vl_mask_folder = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_vl_mask_folder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_vl_mask_folder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_vl_mask_folder.setObjectName("f_vl_mask_folder")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_vl_mask_folder)
        self.verticalLayout_3.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.t_mask_folder_info_header = QtWidgets.QLabel(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_mask_folder_info_header.sizePolicy().hasHeightForWidth())
        self.t_mask_folder_info_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_mask_folder_info_header.setFont(font)
        self.t_mask_folder_info_header.setWordWrap(True)
        self.t_mask_folder_info_header.setObjectName("t_mask_folder_info_header")
        self.verticalLayout_3.addWidget(self.t_mask_folder_info_header)
        self.hl_mask_folder = QtWidgets.QHBoxLayout()
        self.hl_mask_folder.setContentsMargins(2, 2, 2, 2)
        self.hl_mask_folder.setObjectName("hl_mask_folder")
        self.vl_mask_folder_left = QtWidgets.QVBoxLayout()
        self.vl_mask_folder_left.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_folder_left.setObjectName("vl_mask_folder_left")
        self.b_choose_mask_folder = QtWidgets.QPushButton(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_mask_folder.sizePolicy().hasHeightForWidth())
        self.b_choose_mask_folder.setSizePolicy(sizePolicy)
        self.b_choose_mask_folder.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_mask_folder.setObjectName("b_choose_mask_folder")
        self.vl_mask_folder_left.addWidget(self.b_choose_mask_folder)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_mask_folder_left.addItem(spacerItem3)
        self.hl_mask_folder.addLayout(self.vl_mask_folder_left)
        self.vl_mask_folder_right = QtWidgets.QVBoxLayout()
        self.vl_mask_folder_right.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_folder_right.setObjectName("vl_mask_folder_right")
        self.t_found_masks = QtWidgets.QLabel(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_found_masks.sizePolicy().hasHeightForWidth())
        self.t_found_masks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.t_found_masks.setFont(font)
        self.t_found_masks.setObjectName("t_found_masks")
        self.vl_mask_folder_right.addWidget(self.t_found_masks)
        self.scrollArea = QtWidgets.QScrollArea(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_area_found_masks = QtWidgets.QWidget()
        self.scroll_area_found_masks.setGeometry(QtCore.QRect(0, 0, 276, 69))
        self.scroll_area_found_masks.setObjectName("scroll_area_found_masks")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scroll_area_found_masks)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setContentsMargins(0, 1, 1, 1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.t_found_mask_placeholder1 = QtWidgets.QLabel(self.scroll_area_found_masks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_found_mask_placeholder1.sizePolicy().hasHeightForWidth())
        self.t_found_mask_placeholder1.setSizePolicy(sizePolicy)
        self.t_found_mask_placeholder1.setObjectName("t_found_mask_placeholder1")
        self.verticalLayout_9.addWidget(self.t_found_mask_placeholder1)
        self.t_found_mask_placeholder2 = QtWidgets.QLabel(self.scroll_area_found_masks)
        self.t_found_mask_placeholder2.setObjectName("t_found_mask_placeholder2")
        self.verticalLayout_9.addWidget(self.t_found_mask_placeholder2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.scrollArea.setWidget(self.scroll_area_found_masks)
        self.vl_mask_folder_right.addWidget(self.scrollArea)
        self.hl_mask_folder.addLayout(self.vl_mask_folder_right)
        self.verticalLayout_3.addLayout(self.hl_mask_folder)
        self.vl_image_mask.addWidget(self.f_vl_mask_folder)
        self.gridLayout.addLayout(self.vl_image_mask, 1, 0, 1, 1)
        self.vl_image = QtWidgets.QVBoxLayout()
        self.vl_image.setContentsMargins(2, 2, 2, 2)
        self.vl_image.setObjectName("vl_image")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.t_image = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image.sizePolicy().hasHeightForWidth())
        self.t_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image.setFont(font)
        self.t_image.setObjectName("t_image")
        self.horizontalLayout_9.addWidget(self.t_image)
        self.t_image_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_desc.setFont(font)
        self.t_image_desc.setWordWrap(True)
        self.t_image_desc.setObjectName("t_image_desc")
        self.horizontalLayout_9.addWidget(self.t_image_desc)
        self.vl_image.addLayout(self.horizontalLayout_9)
        self.hl_Image = QtWidgets.QHBoxLayout()
        self.hl_Image.setContentsMargins(2, 2, 2, 2)
        self.hl_Image.setObjectName("hl_Image")
        self.vl_left = QtWidgets.QVBoxLayout()
        self.vl_left.setContentsMargins(1, 1, 1, 1)
        self.vl_left.setObjectName("vl_left")
        self.b_choose_image = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_image.sizePolicy().hasHeightForWidth())
        self.b_choose_image.setSizePolicy(sizePolicy)
        self.b_choose_image.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_image.setObjectName("b_choose_image")
        self.vl_left.addWidget(self.b_choose_image)
        self.b_load_current = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_load_current.sizePolicy().hasHeightForWidth())
        self.b_load_current.setSizePolicy(sizePolicy)
        self.b_load_current.setMinimumSize(QtCore.QSize(100, 30))
        self.b_load_current.setObjectName("b_load_current")
        self.vl_left.addWidget(self.b_load_current)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_left.addItem(spacerItem5)
        self.hl_Image.addLayout(self.vl_left)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hl_Image.addItem(spacerItem6)
        self.vl_right = QtWidgets.QVBoxLayout()
        self.vl_right.setContentsMargins(2, 2, 2, 2)
        self.vl_right.setObjectName("vl_right")
        self.l_loaded_image_preview = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_loaded_image_preview.sizePolicy().hasHeightForWidth())
        self.l_loaded_image_preview.setSizePolicy(sizePolicy)
        self.l_loaded_image_preview.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_loaded_image_preview.setFont(font)
        self.l_loaded_image_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.l_loaded_image_preview.setScaledContents(True)
        self.l_loaded_image_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loaded_image_preview.setObjectName("l_loaded_image_preview")
        self.vl_right.addWidget(self.l_loaded_image_preview)
        self.hl_Image.addLayout(self.vl_right)
        self.vl_image.addLayout(self.hl_Image)
        self.gridLayout.addLayout(self.vl_image, 0, 0, 1, 1)
        self.vl_interval_function = QtWidgets.QVBoxLayout()
        self.vl_interval_function.setContentsMargins(2, 2, 2, 2)
        self.vl_interval_function.setObjectName("vl_interval_function")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t_interval_sorting = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_interval_sorting.sizePolicy().hasHeightForWidth())
        self.t_interval_sorting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_interval_sorting.setFont(font)
        self.t_interval_sorting.setObjectName("t_interval_sorting")
        self.horizontalLayout_2.addWidget(self.t_interval_sorting)
        self.t_interval_sorting_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_interval_sorting_desc.setFont(font)
        self.t_interval_sorting_desc.setObjectName("t_interval_sorting_desc")
        self.horizontalLayout_2.addWidget(self.t_interval_sorting_desc)
        self.vl_interval_function.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cb_interval_function = QtWidgets.QComboBox(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_interval_function.sizePolicy().hasHeightForWidth())
        self.cb_interval_function.setSizePolicy(sizePolicy)
        self.cb_interval_function.setMinimumSize(QtCore.QSize(80, 0))
        self.cb_interval_function.setEditable(False)
        self.cb_interval_function.setFrame(True)
        self.cb_interval_function.setObjectName("cb_interval_function")
        self.cb_interval_function.addItem("")
        self.cb_interval_function.addItem("")
        self.horizontalLayout_7.addWidget(self.cb_interval_function)
        self.t_interval_function_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_interval_function_desc.setFont(font)
        self.t_interval_function_desc.setObjectName("t_interval_function_desc")
        self.horizontalLayout_7.addWidget(self.t_interval_function_desc)
        self.vl_interval_function.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vl_interval_function.addWidget(self.line)
        self.t_parameters = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_parameters.sizePolicy().hasHeightForWidth())
        self.t_parameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.t_parameters.setFont(font)
        self.t_parameters.setObjectName("t_parameters")
        self.vl_interval_function.addWidget(self.t_parameters)
        self.f_param_random = QtWidgets.QFrame(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_param_random.sizePolicy().hasHeightForWidth())
        self.f_param_random.setSizePolicy(sizePolicy)
        self.f_param_random.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_random.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_random.setObjectName("f_param_random")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.f_param_random)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hl_param_randomness_t = QtWidgets.QHBoxLayout()
        self.hl_param_randomness_t.setSpacing(10)
        self.hl_param_randomness_t.setObjectName("hl_param_randomness_t")
        self.t_param_randomness = QtWidgets.QLabel(self.f_param_random)
        self.t_param_randomness.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_randomness.setObjectName("t_param_randomness")
        self.hl_param_randomness_t.addWidget(self.t_param_randomness)
        self.t_param_randomness_desc = QtWidgets.QLabel(self.f_param_random)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_randomness_desc.sizePolicy().hasHeightForWidth())
        self.t_param_randomness_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_randomness_desc.setFont(font)
        self.t_param_randomness_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_randomness_desc.setObjectName("t_param_randomness_desc")
        self.hl_param_randomness_t.addWidget(self.t_param_randomness_desc)
        self.verticalLayout_4.addLayout(self.hl_param_randomness_t)
        self.hl_param_randomness_b = QtWidgets.QHBoxLayout()
        self.hl_param_randomness_b.setObjectName("hl_param_randomness_b")
        self.t_param_randomness_value = QtWidgets.QLabel(self.f_param_random)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_randomness_value.sizePolicy().hasHeightForWidth())
        self.t_param_randomness_value.setSizePolicy(sizePolicy)
        self.t_param_randomness_value.setObjectName("t_param_randomness_value")
        self.hl_param_randomness_b.addWidget(self.t_param_randomness_value)
        self.slider_param_randomness = QtWidgets.QSlider(self.f_param_random)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_randomness.sizePolicy().hasHeightForWidth())
        self.slider_param_randomness.setSizePolicy(sizePolicy)
        self.slider_param_randomness.setMaximum(100)
        self.slider_param_randomness.setProperty("value", 0)
        self.slider_param_randomness.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_randomness.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_randomness.setTickInterval(10)
        self.slider_param_randomness.setObjectName("slider_param_randomness")
        self.hl_param_randomness_b.addWidget(self.slider_param_randomness)
        self.verticalLayout_4.addLayout(self.hl_param_randomness_b)
        self.vl_interval_function.addWidget(self.f_param_random)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_interval_function.addItem(spacerItem7)
        self.f_param_thresh_l = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_param_thresh_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_thresh_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_thresh_l.setObjectName("f_param_thresh_l")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.f_param_thresh_l)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hl_param_thresh_l_t = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_l_t.setSpacing(10)
        self.hl_param_thresh_l_t.setObjectName("hl_param_thresh_l_t")
        self.t_param_thresh_l = QtWidgets.QLabel(self.f_param_thresh_l)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_l.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_l.setSizePolicy(sizePolicy)
        self.t_param_thresh_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_l.setObjectName("t_param_thresh_l")
        self.hl_param_thresh_l_t.addWidget(self.t_param_thresh_l)
        self.t_param_thresh_l_desc = QtWidgets.QLabel(self.f_param_thresh_l)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_l_desc.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_l_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_thresh_l_desc.setFont(font)
        self.t_param_thresh_l_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_l_desc.setWordWrap(True)
        self.t_param_thresh_l_desc.setObjectName("t_param_thresh_l_desc")
        self.hl_param_thresh_l_t.addWidget(self.t_param_thresh_l_desc)
        self.verticalLayout_5.addLayout(self.hl_param_thresh_l_t)
        self.hl_param_thresh_l_b = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_l_b.setSpacing(6)
        self.hl_param_thresh_l_b.setObjectName("hl_param_thresh_l_b")
        self.t_param_thresh_l_value = QtWidgets.QLabel(self.f_param_thresh_l)
        self.t_param_thresh_l_value.setObjectName("t_param_thresh_l_value")
        self.hl_param_thresh_l_b.addWidget(self.t_param_thresh_l_value)
        self.slider_param_thresh_l = QtWidgets.QSlider(self.f_param_thresh_l)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_thresh_l.sizePolicy().hasHeightForWidth())
        self.slider_param_thresh_l.setSizePolicy(sizePolicy)
        self.slider_param_thresh_l.setMaximum(100)
        self.slider_param_thresh_l.setSingleStep(1)
        self.slider_param_thresh_l.setProperty("value", 0)
        self.slider_param_thresh_l.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_thresh_l.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_thresh_l.setTickInterval(10)
        self.slider_param_thresh_l.setObjectName("slider_param_thresh_l")
        self.hl_param_thresh_l_b.addWidget(self.slider_param_thresh_l)
        self.verticalLayout_5.addLayout(self.hl_param_thresh_l_b)
        self.vl_interval_function.addWidget(self.f_param_thresh_l)
        self.f_param_thresh_u = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_param_thresh_u.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_thresh_u.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_thresh_u.setObjectName("f_param_thresh_u")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.f_param_thresh_u)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hl_param_thresh_u_t = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_u_t.setSpacing(10)
        self.hl_param_thresh_u_t.setObjectName("hl_param_thresh_u_t")
        self.t_param_thresh_u = QtWidgets.QLabel(self.f_param_thresh_u)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_u.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_u.setSizePolicy(sizePolicy)
        self.t_param_thresh_u.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_u.setObjectName("t_param_thresh_u")
        self.hl_param_thresh_u_t.addWidget(self.t_param_thresh_u)
        self.t_param_thresh_u_desc = QtWidgets.QLabel(self.f_param_thresh_u)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_u_desc.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_u_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_thresh_u_desc.setFont(font)
        self.t_param_thresh_u_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_u_desc.setWordWrap(True)
        self.t_param_thresh_u_desc.setObjectName("t_param_thresh_u_desc")
        self.hl_param_thresh_u_t.addWidget(self.t_param_thresh_u_desc)
        self.verticalLayout_6.addLayout(self.hl_param_thresh_u_t)
        self.hl_param_thresh_u_b = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_u_b.setObjectName("hl_param_thresh_u_b")
        self.t_param_thresh_u_value = QtWidgets.QLabel(self.f_param_thresh_u)
        self.t_param_thresh_u_value.setObjectName("t_param_thresh_u_value")
        self.hl_param_thresh_u_b.addWidget(self.t_param_thresh_u_value)
        self.slider_param_thresh_u = QtWidgets.QSlider(self.f_param_thresh_u)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_thresh_u.sizePolicy().hasHeightForWidth())
        self.slider_param_thresh_u.setSizePolicy(sizePolicy)
        self.slider_param_thresh_u.setMaximum(100)
        self.slider_param_thresh_u.setSingleStep(1)
        self.slider_param_thresh_u.setProperty("value", 0)
        self.slider_param_thresh_u.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_thresh_u.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_thresh_u.setTickInterval(10)
        self.slider_param_thresh_u.setObjectName("slider_param_thresh_u")
        self.hl_param_thresh_u_b.addWidget(self.slider_param_thresh_u)
        self.verticalLayout_6.addLayout(self.hl_param_thresh_u_b)
        self.vl_interval_function.addWidget(self.f_param_thresh_u)
        self.f_param_clength = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_param_clength.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_clength.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_clength.setObjectName("f_param_clength")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.f_param_clength)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.hl_param_clength_t = QtWidgets.QHBoxLayout()
        self.hl_param_clength_t.setSpacing(10)
        self.hl_param_clength_t.setObjectName("hl_param_clength_t")
        self.t_param_clength = QtWidgets.QLabel(self.f_param_clength)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_clength.sizePolicy().hasHeightForWidth())
        self.t_param_clength.setSizePolicy(sizePolicy)
        self.t_param_clength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_clength.setObjectName("t_param_clength")
        self.hl_param_clength_t.addWidget(self.t_param_clength)
        self.t_param_clength_desc = QtWidgets.QLabel(self.f_param_clength)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_clength_desc.sizePolicy().hasHeightForWidth())
        self.t_param_clength_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_clength_desc.setFont(font)
        self.t_param_clength_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_clength_desc.setWordWrap(True)
        self.t_param_clength_desc.setObjectName("t_param_clength_desc")
        self.hl_param_clength_t.addWidget(self.t_param_clength_desc)
        self.verticalLayout_7.addLayout(self.hl_param_clength_t)
        self.hl_param_clength_b = QtWidgets.QHBoxLayout()
        self.hl_param_clength_b.setObjectName("hl_param_clength_b")
        self.t_param_clength_helper = QtWidgets.QLabel(self.f_param_clength)
        self.t_param_clength_helper.setObjectName("t_param_clength_helper")
        self.hl_param_clength_b.addWidget(self.t_param_clength_helper)
        self.tb_param_clength = QtWidgets.QLineEdit(self.f_param_clength)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_param_clength.sizePolicy().hasHeightForWidth())
        self.tb_param_clength.setSizePolicy(sizePolicy)
        self.tb_param_clength.setMinimumSize(QtCore.QSize(20, 0))
        self.tb_param_clength.setMaximumSize(QtCore.QSize(35, 16777215))
        self.tb_param_clength.setText("")
        self.tb_param_clength.setObjectName("tb_param_clength")
        self.hl_param_clength_b.addWidget(self.tb_param_clength)
        spacerItem8 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_param_clength_b.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.hl_param_clength_b)
        self.vl_interval_function.addWidget(self.f_param_clength)
        self.f_param_angle = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_param_angle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_angle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_angle.setObjectName("f_param_angle")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.f_param_angle)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.hl_param_angle_t = QtWidgets.QHBoxLayout()
        self.hl_param_angle_t.setSpacing(10)
        self.hl_param_angle_t.setObjectName("hl_param_angle_t")
        self.t_param_angle = QtWidgets.QLabel(self.f_param_angle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_angle.sizePolicy().hasHeightForWidth())
        self.t_param_angle.setSizePolicy(sizePolicy)
        self.t_param_angle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_angle.setObjectName("t_param_angle")
        self.hl_param_angle_t.addWidget(self.t_param_angle)
        self.t_param_angle_desc = QtWidgets.QLabel(self.f_param_angle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_angle_desc.sizePolicy().hasHeightForWidth())
        self.t_param_angle_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_angle_desc.setFont(font)
        self.t_param_angle_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_angle_desc.setWordWrap(True)
        self.t_param_angle_desc.setObjectName("t_param_angle_desc")
        self.hl_param_angle_t.addWidget(self.t_param_angle_desc)
        self.verticalLayout_8.addLayout(self.hl_param_angle_t)
        self.hl_param_angle_b = QtWidgets.QHBoxLayout()
        self.hl_param_angle_b.setObjectName("hl_param_angle_b")
        self.t_param_angle_value = QtWidgets.QLabel(self.f_param_angle)
        self.t_param_angle_value.setObjectName("t_param_angle_value")
        self.hl_param_angle_b.addWidget(self.t_param_angle_value)
        self.slider_param_angle = QtWidgets.QSlider(self.f_param_angle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_angle.sizePolicy().hasHeightForWidth())
        self.slider_param_angle.setSizePolicy(sizePolicy)
        self.slider_param_angle.setMaximum(360)
        self.slider_param_angle.setSingleStep(1)
        self.slider_param_angle.setProperty("value", 0)
        self.slider_param_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_angle.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_angle.setTickInterval(15)
        self.slider_param_angle.setObjectName("slider_param_angle")
        self.hl_param_angle_b.addWidget(self.slider_param_angle)
        self.verticalLayout_8.addLayout(self.hl_param_angle_b)
        self.vl_interval_function.addWidget(self.f_param_angle)
        self.gridLayout.addLayout(self.vl_interval_function, 2, 0, 1, 1)
        self.vl_pixel_ordering = QtWidgets.QVBoxLayout()
        self.vl_pixel_ordering.setContentsMargins(2, 2, 2, 2)
        self.vl_pixel_ordering.setObjectName("vl_pixel_ordering")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.t_pixel_ordering = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_pixel_ordering.setFont(font)
        self.t_pixel_ordering.setObjectName("t_pixel_ordering")
        self.horizontalLayout_5.addWidget(self.t_pixel_ordering)
        self.t_pixel_ordering_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_pixel_ordering_desc.setFont(font)
        self.t_pixel_ordering_desc.setWordWrap(True)
        self.t_pixel_ordering_desc.setObjectName("t_pixel_ordering_desc")
        self.horizontalLayout_5.addWidget(self.t_pixel_ordering_desc)
        self.vl_pixel_ordering.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cb_pixel_ordering_option = QtWidgets.QComboBox(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_pixel_ordering_option.sizePolicy().hasHeightForWidth())
        self.cb_pixel_ordering_option.setSizePolicy(sizePolicy)
        self.cb_pixel_ordering_option.setMinimumSize(QtCore.QSize(80, 0))
        self.cb_pixel_ordering_option.setEditable(False)
        self.cb_pixel_ordering_option.setFrame(True)
        self.cb_pixel_ordering_option.setObjectName("cb_pixel_ordering_option")
        self.cb_pixel_ordering_option.addItem("")
        self.cb_pixel_ordering_option.addItem("")
        self.horizontalLayout_6.addWidget(self.cb_pixel_ordering_option)
        self.t_pixel_ordering_option_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering_option_desc.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering_option_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_pixel_ordering_option_desc.setFont(font)
        self.t_pixel_ordering_option_desc.setObjectName("t_pixel_ordering_option_desc")
        self.horizontalLayout_6.addWidget(self.t_pixel_ordering_option_desc)
        self.vl_pixel_ordering.addLayout(self.horizontalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_pixel_ordering.addItem(spacerItem9)
        self.gridLayout.addLayout(self.vl_pixel_ordering, 3, 0, 1, 1)
        self.vl_generation = QtWidgets.QVBoxLayout()
        self.vl_generation.setContentsMargins(2, 2, 2, 2)
        self.vl_generation.setObjectName("vl_generation")
        self.hl_generation = QtWidgets.QHBoxLayout()
        self.hl_generation.setObjectName("hl_generation")
        self.b_generate_preview = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_generate_preview.sizePolicy().hasHeightForWidth())
        self.b_generate_preview.setSizePolicy(sizePolicy)
        self.b_generate_preview.setMinimumSize(QtCore.QSize(100, 30))
        self.b_generate_preview.setObjectName("b_generate_preview")
        self.hl_generation.addWidget(self.b_generate_preview)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_generation.addItem(spacerItem10)
        self.b_generate_full = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_generate_full.sizePolicy().hasHeightForWidth())
        self.b_generate_full.setSizePolicy(sizePolicy)
        self.b_generate_full.setMinimumSize(QtCore.QSize(100, 30))
        self.b_generate_full.setObjectName("b_generate_full")
        self.hl_generation.addWidget(self.b_generate_full)
        self.vl_generation.addLayout(self.hl_generation)
        self.gridLayout.addLayout(self.vl_generation, 5, 0, 1, 1)
        self.vl_save_location = QtWidgets.QVBoxLayout()
        self.vl_save_location.setContentsMargins(2, 2, 2, 2)
        self.vl_save_location.setObjectName("vl_save_location")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.t_save_location = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location.sizePolicy().hasHeightForWidth())
        self.t_save_location.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_save_location.setFont(font)
        self.t_save_location.setObjectName("t_save_location")
        self.horizontalLayout_4.addWidget(self.t_save_location)
        self.t_save_location_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_desc.setFont(font)
        self.t_save_location_desc.setWordWrap(True)
        self.t_save_location_desc.setObjectName("t_save_location_desc")
        self.horizontalLayout_4.addWidget(self.t_save_location_desc)
        self.vl_save_location.addLayout(self.horizontalLayout_4)
        self.hl_save_location = QtWidgets.QHBoxLayout()
        self.hl_save_location.setObjectName("hl_save_location")
        self.b_save_location = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save_location.sizePolicy().hasHeightForWidth())
        self.b_save_location.setSizePolicy(sizePolicy)
        self.b_save_location.setMinimumSize(QtCore.QSize(100, 30))
        self.b_save_location.setObjectName("b_save_location")
        self.hl_save_location.addWidget(self.b_save_location)
        self.t_save_location_current = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location_current.sizePolicy().hasHeightForWidth())
        self.t_save_location_current.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_current.setFont(font)
        self.t_save_location_current.setObjectName("t_save_location_current")
        self.hl_save_location.addWidget(self.t_save_location_current)
        self.vl_save_location.addLayout(self.hl_save_location)
        spacerItem11 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_save_location.addItem(spacerItem11)
        self.gridLayout.addLayout(self.vl_save_location, 4, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem12, 6, 0, 1, 1)
        self.scroll_area_settings.setWidget(self.scroll_area_settings_content)
        self.verticalLayout.addWidget(self.scroll_area_settings)
        self.horizontalLayout.addWidget(self.f_settings_panel)
        self.f_preview_panel = QtWidgets.QFrame(self.centralwidget)
        self.f_preview_panel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_preview_panel.sizePolicy().hasHeightForWidth())
        self.f_preview_panel.setSizePolicy(sizePolicy)
        self.f_preview_panel.setAutoFillBackground(False)
        self.f_preview_panel.setFrameShape(QtWidgets.QFrame.Panel)
        self.f_preview_panel.setObjectName("f_preview_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_preview_panel)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl_image_preview = QtWidgets.QHBoxLayout()
        self.hl_image_preview.setObjectName("hl_image_preview")
        self.cb_live_preview = QtWidgets.QCheckBox(self.f_preview_panel)
        self.cb_live_preview.setObjectName("cb_live_preview")
        self.hl_image_preview.addWidget(self.cb_live_preview)
        self.verticalLayout_2.addLayout(self.hl_image_preview)
        self.line_2 = QtWidgets.QFrame(self.f_preview_panel)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.l_generated_image = QtWidgets.QLabel(self.f_preview_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_generated_image.sizePolicy().hasHeightForWidth())
        self.l_generated_image.setSizePolicy(sizePolicy)
        self.l_generated_image.setText("")
        self.l_generated_image.setScaledContents(True)
        self.l_generated_image.setAlignment(QtCore.Qt.AlignCenter)
        self.l_generated_image.setObjectName("l_generated_image")
        self.verticalLayout_2.addWidget(self.l_generated_image)
        spacerItem13 = QtWidgets.QSpacerItem(957, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem13)
        self.horizontalLayout.addWidget(self.f_preview_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhi = QtWidgets.QAction(MainWindow)
        self.actionhi.setObjectName("actionhi")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.t_image_mask.setText(QtWidgets.QApplication.translate("MainWindow", "Image Mask", None, -1))
        self.t_image_mask_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.rb_mask_none.setText(QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.rb_mask_single.setText(QtWidgets.QApplication.translate("MainWindow", "Single Mask", None, -1))
        self.rb_mask_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Mask from Folder", None, -1))
        self.t_no_mask.setText(QtWidgets.QApplication.translate("MainWindow", "No mask image will be used.", None, -1))
        self.b_choose_mask.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Image", None, -1))
        self.l_loaded_mask_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Loaded mask will display here", None, -1))
        self.t_mask_folder_info_header.setText(QtWidgets.QApplication.translate("MainWindow", "Note: If the loaded image is in found in the mask folder it will be ignored.", None, -1))
        self.b_choose_mask_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Folder", None, -1))
        self.t_found_masks.setText(QtWidgets.QApplication.translate("MainWindow", "Found Masks:", None, -1))
        self.t_found_mask_placeholder1.setText(QtWidgets.QApplication.translate("MainWindow", "placeholder1", None, -1))
        self.t_found_mask_placeholder2.setText(QtWidgets.QApplication.translate("MainWindow", "placeholder2", None, -1))
        self.t_image.setText(QtWidgets.QApplication.translate("MainWindow", "Image", None, -1))
        self.t_image_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.b_choose_image.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Image", None, -1))
        self.b_load_current.setText(QtWidgets.QApplication.translate("MainWindow", "Load Current", None, -1))
        self.l_loaded_image_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Loaded image will display here", None, -1))
        self.t_interval_sorting.setText(QtWidgets.QApplication.translate("MainWindow", "Interval Sorting", None, -1))
        self.t_interval_sorting_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.cb_interval_function.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "option 1", None, -1))
        self.cb_interval_function.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "option 2", None, -1))
        self.t_interval_function_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.t_parameters.setText(QtWidgets.QApplication.translate("MainWindow", "Parameters", None, -1))
        self.t_param_randomness.setText(QtWidgets.QApplication.translate("MainWindow", "Randomness", None, -1))
        self.t_param_randomness_desc.setText(QtWidgets.QApplication.translate("MainWindow", "What percentage of intervals not to sort. 0 by default.", None, -1))
        self.t_param_randomness_value.setText(QtWidgets.QApplication.translate("MainWindow", "rand val", None, -1))
        self.t_param_thresh_l.setText(QtWidgets.QApplication.translate("MainWindow", "Threshold (lower)", None, -1))
        self.t_param_thresh_l_desc.setText(QtWidgets.QApplication.translate("MainWindow", "How dark must a pixel be to be considered as a \'border\' for sorting? Takes values from 0-1. 0.25 by default. Used in edges and threshold modes.", None, -1))
        self.t_param_thresh_l_value.setText(QtWidgets.QApplication.translate("MainWindow", "thresh (l) val", None, -1))
        self.t_param_thresh_u.setText(QtWidgets.QApplication.translate("MainWindow", "Threshold (upper)", None, -1))
        self.t_param_thresh_u_desc.setText(QtWidgets.QApplication.translate("MainWindow", "How bright must a pixel be to be considered as a \'border\' for sorting? Takes values from 0-1. 0.8 by default. Used in threshold mode.", None, -1))
        self.t_param_thresh_u_value.setText(QtWidgets.QApplication.translate("MainWindow", "thresh (u) val", None, -1))
        self.t_param_clength.setText(QtWidgets.QApplication.translate("MainWindow", "Char. length", None, -1))
        self.t_param_clength_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Characteristic length for the random width generator. Used in mode random and waves.", None, -1))
        self.t_param_clength_helper.setText(QtWidgets.QApplication.translate("MainWindow", "(0 - inf)", None, -1))
        self.t_param_angle.setText(QtWidgets.QApplication.translate("MainWindow", "Angle", None, -1))
        self.t_param_angle_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Angle at which you\'re pixel sorting in degrees. 0 (horizontal) by default.", None, -1))
        self.t_param_angle_value.setText(QtWidgets.QApplication.translate("MainWindow", "angle val", None, -1))
        self.t_pixel_ordering.setText(QtWidgets.QApplication.translate("MainWindow", "Pixel Ordering", None, -1))
        self.t_pixel_ordering_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.cb_pixel_ordering_option.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "option 1", None, -1))
        self.cb_pixel_ordering_option.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "option 2", None, -1))
        self.t_pixel_ordering_option_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.b_generate_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Preview", None, -1))
        self.b_generate_full.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Full", None, -1))
        self.t_save_location.setText(QtWidgets.QApplication.translate("MainWindow", "Save Location", None, -1))
        self.t_save_location_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.b_save_location.setText(QtWidgets.QApplication.translate("MainWindow", "Save Location", None, -1))
        self.t_save_location_current.setText(QtWidgets.QApplication.translate("MainWindow", "(save location)", None, -1))
        self.cb_live_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Live Preview", None, -1))
        self.actionhi.setText(QtWidgets.QApplication.translate("MainWindow", "hi", None, -1))

