# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DHUIZING\Documents\GitHub\pixelsort\pixel_sorter_gui.ui',
# licensing of 'c:\Users\DHUIZING\Documents\GitHub\pixelsort\pixel_sorter_gui.ui' applies.
#
# Created: Thu Sep 10 17:00:56 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 745)
        MainWindow.setMaximumSize(QtCore.QSize(1500, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.f_settings_panel = QtWidgets.QFrame(self.centralwidget)
        self.f_settings_panel.setMaximumSize(QtCore.QSize(600, 16777215))
        self.f_settings_panel.setFrameShape(QtWidgets.QFrame.Panel)
        self.f_settings_panel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_settings_panel.setLineWidth(1)
        self.f_settings_panel.setObjectName("f_settings_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_settings_panel)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(2, 2, 0, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area_settings = QtWidgets.QScrollArea(self.f_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_settings.sizePolicy().hasHeightForWidth())
        self.scroll_area_settings.setSizePolicy(sizePolicy)
        self.scroll_area_settings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area_settings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area_settings.setWidgetResizable(True)
        self.scroll_area_settings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scroll_area_settings.setObjectName("scroll_area_settings")
        self.scroll_area_settings_content = QtWidgets.QWidget()
        self.scroll_area_settings_content.setGeometry(QtCore.QRect(0, 0, 413, 696))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_settings_content.sizePolicy().hasHeightForWidth())
        self.scroll_area_settings_content.setSizePolicy(sizePolicy)
        self.scroll_area_settings_content.setObjectName("scroll_area_settings_content")
        self.gridLayout = QtWidgets.QGridLayout(self.scroll_area_settings_content)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vl_image_mask = QtWidgets.QVBoxLayout()
        self.vl_image_mask.setSpacing(2)
        self.vl_image_mask.setContentsMargins(2, 2, 2, 2)
        self.vl_image_mask.setObjectName("vl_image_mask")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.t_image_mask = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_mask.sizePolicy().hasHeightForWidth())
        self.t_image_mask.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image_mask.setFont(font)
        self.t_image_mask.setObjectName("t_image_mask")
        self.horizontalLayout_8.addWidget(self.t_image_mask)
        self.t_image_mask_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_mask_desc.sizePolicy().hasHeightForWidth())
        self.t_image_mask_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_mask_desc.setFont(font)
        self.t_image_mask_desc.setWordWrap(True)
        self.t_image_mask_desc.setObjectName("t_image_mask_desc")
        self.horizontalLayout_8.addWidget(self.t_image_mask_desc)
        self.vl_image_mask.addLayout(self.horizontalLayout_8)
        self.hl_mask_selection = QtWidgets.QHBoxLayout()
        self.hl_mask_selection.setObjectName("hl_mask_selection")
        self.rb_mask_none = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_none.sizePolicy().hasHeightForWidth())
        self.rb_mask_none.setSizePolicy(sizePolicy)
        self.rb_mask_none.setObjectName("rb_mask_none")
        self.hl_mask_selection.addWidget(self.rb_mask_none)
        self.rb_mask_single = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_single.sizePolicy().hasHeightForWidth())
        self.rb_mask_single.setSizePolicy(sizePolicy)
        self.rb_mask_single.setChecked(True)
        self.rb_mask_single.setObjectName("rb_mask_single")
        self.hl_mask_selection.addWidget(self.rb_mask_single)
        self.rb_mask_folder = QtWidgets.QRadioButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mask_folder.sizePolicy().hasHeightForWidth())
        self.rb_mask_folder.setSizePolicy(sizePolicy)
        self.rb_mask_folder.setObjectName("rb_mask_folder")
        self.hl_mask_selection.addWidget(self.rb_mask_folder)
        self.vl_image_mask.addLayout(self.hl_mask_selection)
        self.f_hl_mask_none = QtWidgets.QFrame(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_hl_mask_none.sizePolicy().hasHeightForWidth())
        self.f_hl_mask_none.setSizePolicy(sizePolicy)
        self.f_hl_mask_none.setFrameShape(QtWidgets.QFrame.Box)
        self.f_hl_mask_none.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_hl_mask_none.setObjectName("f_hl_mask_none")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.f_hl_mask_none)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t_no_mask = QtWidgets.QLabel(self.f_hl_mask_none)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_no_mask.sizePolicy().hasHeightForWidth())
        self.t_no_mask.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_no_mask.setFont(font)
        self.t_no_mask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_no_mask.setObjectName("t_no_mask")
        self.horizontalLayout_11.addWidget(self.t_no_mask)
        self.vl_image_mask.addWidget(self.f_hl_mask_none)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_image_mask.addItem(spacerItem)
        self.f_hl_mask_single = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_hl_mask_single.setFrameShape(QtWidgets.QFrame.Box)
        self.f_hl_mask_single.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_hl_mask_single.setObjectName("f_hl_mask_single")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.f_hl_mask_single)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.vl_mask_single_left = QtWidgets.QVBoxLayout()
        self.vl_mask_single_left.setContentsMargins(1, 1, 1, 1)
        self.vl_mask_single_left.setObjectName("vl_mask_single_left")
        self.b_choose_mask = QtWidgets.QPushButton(self.f_hl_mask_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_mask.sizePolicy().hasHeightForWidth())
        self.b_choose_mask.setSizePolicy(sizePolicy)
        self.b_choose_mask.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_mask.setObjectName("b_choose_mask")
        self.vl_mask_single_left.addWidget(self.b_choose_mask)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_mask_single_left.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.vl_mask_single_left)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.vl_mask_single_right = QtWidgets.QVBoxLayout()
        self.vl_mask_single_right.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_single_right.setObjectName("vl_mask_single_right")
        self.l_loaded_mask_preview = QtWidgets.QLabel(self.f_hl_mask_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_loaded_mask_preview.sizePolicy().hasHeightForWidth())
        self.l_loaded_mask_preview.setSizePolicy(sizePolicy)
        self.l_loaded_mask_preview.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_loaded_mask_preview.setFont(font)
        self.l_loaded_mask_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.l_loaded_mask_preview.setScaledContents(True)
        self.l_loaded_mask_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loaded_mask_preview.setObjectName("l_loaded_mask_preview")
        self.vl_mask_single_right.addWidget(self.l_loaded_mask_preview)
        self.horizontalLayout_12.addLayout(self.vl_mask_single_right)
        self.vl_image_mask.addWidget(self.f_hl_mask_single)
        self.f_vl_mask_folder = QtWidgets.QFrame(self.scroll_area_settings_content)
        self.f_vl_mask_folder.setFrameShape(QtWidgets.QFrame.Box)
        self.f_vl_mask_folder.setFrameShadow(QtWidgets.QFrame.Plain)
        self.f_vl_mask_folder.setObjectName("f_vl_mask_folder")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_vl_mask_folder)
        self.verticalLayout_3.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.t_mask_folder_info_header = QtWidgets.QLabel(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_mask_folder_info_header.sizePolicy().hasHeightForWidth())
        self.t_mask_folder_info_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_mask_folder_info_header.setFont(font)
        self.t_mask_folder_info_header.setWordWrap(True)
        self.t_mask_folder_info_header.setObjectName("t_mask_folder_info_header")
        self.verticalLayout_3.addWidget(self.t_mask_folder_info_header)
        self.hl_mask_folder = QtWidgets.QHBoxLayout()
        self.hl_mask_folder.setContentsMargins(2, 2, 2, 2)
        self.hl_mask_folder.setObjectName("hl_mask_folder")
        self.vl_mask_folder_left = QtWidgets.QVBoxLayout()
        self.vl_mask_folder_left.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_folder_left.setObjectName("vl_mask_folder_left")
        self.b_choose_mask_folder = QtWidgets.QPushButton(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_mask_folder.sizePolicy().hasHeightForWidth())
        self.b_choose_mask_folder.setSizePolicy(sizePolicy)
        self.b_choose_mask_folder.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_mask_folder.setObjectName("b_choose_mask_folder")
        self.vl_mask_folder_left.addWidget(self.b_choose_mask_folder)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_mask_folder_left.addItem(spacerItem3)
        self.hl_mask_folder.addLayout(self.vl_mask_folder_left)
        self.vl_mask_folder_right = QtWidgets.QVBoxLayout()
        self.vl_mask_folder_right.setContentsMargins(2, 2, 2, 2)
        self.vl_mask_folder_right.setObjectName("vl_mask_folder_right")
        self.t_found_masks = QtWidgets.QLabel(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_found_masks.sizePolicy().hasHeightForWidth())
        self.t_found_masks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.t_found_masks.setFont(font)
        self.t_found_masks.setObjectName("t_found_masks")
        self.vl_mask_folder_right.addWidget(self.t_found_masks)
        self.scrollArea = QtWidgets.QScrollArea(self.f_vl_mask_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_area_found_masks = QtWidgets.QWidget()
        self.scroll_area_found_masks.setGeometry(QtCore.QRect(0, 0, 287, 69))
        self.scroll_area_found_masks.setObjectName("scroll_area_found_masks")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scroll_area_found_masks)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setContentsMargins(0, 1, 1, 1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.t_found_mask_placeholder1 = QtWidgets.QLabel(self.scroll_area_found_masks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_found_mask_placeholder1.sizePolicy().hasHeightForWidth())
        self.t_found_mask_placeholder1.setSizePolicy(sizePolicy)
        self.t_found_mask_placeholder1.setObjectName("t_found_mask_placeholder1")
        self.verticalLayout_9.addWidget(self.t_found_mask_placeholder1)
        self.t_found_mask_placeholder2 = QtWidgets.QLabel(self.scroll_area_found_masks)
        self.t_found_mask_placeholder2.setObjectName("t_found_mask_placeholder2")
        self.verticalLayout_9.addWidget(self.t_found_mask_placeholder2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.scrollArea.setWidget(self.scroll_area_found_masks)
        self.vl_mask_folder_right.addWidget(self.scrollArea)
        self.hl_mask_folder.addLayout(self.vl_mask_folder_right)
        self.verticalLayout_3.addLayout(self.hl_mask_folder)
        self.vl_image_mask.addWidget(self.f_vl_mask_folder)
        self.gridLayout.addLayout(self.vl_image_mask, 1, 0, 1, 1)
        self.vl_image = QtWidgets.QVBoxLayout()
        self.vl_image.setContentsMargins(2, 2, 2, 2)
        self.vl_image.setObjectName("vl_image")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.t_image = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image.sizePolicy().hasHeightForWidth())
        self.t_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_image.setFont(font)
        self.t_image.setObjectName("t_image")
        self.horizontalLayout_9.addWidget(self.t_image)
        self.t_image_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_image_desc.sizePolicy().hasHeightForWidth())
        self.t_image_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_image_desc.setFont(font)
        self.t_image_desc.setWordWrap(True)
        self.t_image_desc.setObjectName("t_image_desc")
        self.horizontalLayout_9.addWidget(self.t_image_desc)
        self.vl_image.addLayout(self.horizontalLayout_9)
        self.hl_Image = QtWidgets.QHBoxLayout()
        self.hl_Image.setContentsMargins(2, 2, 2, 2)
        self.hl_Image.setObjectName("hl_Image")
        self.vl_left = QtWidgets.QVBoxLayout()
        self.vl_left.setContentsMargins(1, 1, 1, 1)
        self.vl_left.setObjectName("vl_left")
        self.b_choose_image = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_choose_image.sizePolicy().hasHeightForWidth())
        self.b_choose_image.setSizePolicy(sizePolicy)
        self.b_choose_image.setMinimumSize(QtCore.QSize(100, 30))
        self.b_choose_image.setObjectName("b_choose_image")
        self.vl_left.addWidget(self.b_choose_image)
        self.b_load_current = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_load_current.sizePolicy().hasHeightForWidth())
        self.b_load_current.setSizePolicy(sizePolicy)
        self.b_load_current.setMinimumSize(QtCore.QSize(100, 30))
        self.b_load_current.setObjectName("b_load_current")
        self.vl_left.addWidget(self.b_load_current)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vl_left.addItem(spacerItem5)
        self.hl_Image.addLayout(self.vl_left)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hl_Image.addItem(spacerItem6)
        self.vl_right = QtWidgets.QVBoxLayout()
        self.vl_right.setContentsMargins(2, 2, 2, 2)
        self.vl_right.setObjectName("vl_right")
        self.l_loaded_image_preview = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_loaded_image_preview.sizePolicy().hasHeightForWidth())
        self.l_loaded_image_preview.setSizePolicy(sizePolicy)
        self.l_loaded_image_preview.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_loaded_image_preview.setFont(font)
        self.l_loaded_image_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.l_loaded_image_preview.setScaledContents(True)
        self.l_loaded_image_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_loaded_image_preview.setObjectName("l_loaded_image_preview")
        self.vl_right.addWidget(self.l_loaded_image_preview)
        self.hl_Image.addLayout(self.vl_right)
        self.vl_image.addLayout(self.hl_Image)
        self.gridLayout.addLayout(self.vl_image, 0, 0, 1, 1)
        self.vl_interval_function = QtWidgets.QVBoxLayout()
        self.vl_interval_function.setContentsMargins(2, 2, 2, 2)
        self.vl_interval_function.setObjectName("vl_interval_function")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t_interval_sorting = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_interval_sorting.sizePolicy().hasHeightForWidth())
        self.t_interval_sorting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_interval_sorting.setFont(font)
        self.t_interval_sorting.setObjectName("t_interval_sorting")
        self.horizontalLayout_2.addWidget(self.t_interval_sorting)
        self.t_interval_sorting_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_interval_sorting_desc.sizePolicy().hasHeightForWidth())
        self.t_interval_sorting_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_interval_sorting_desc.setFont(font)
        self.t_interval_sorting_desc.setObjectName("t_interval_sorting_desc")
        self.horizontalLayout_2.addWidget(self.t_interval_sorting_desc)
        self.vl_interval_function.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cb_interval_function = QtWidgets.QComboBox(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_interval_function.sizePolicy().hasHeightForWidth())
        self.cb_interval_function.setSizePolicy(sizePolicy)
        self.cb_interval_function.setMinimumSize(QtCore.QSize(70, 0))
        self.cb_interval_function.setEditable(False)
        self.cb_interval_function.setFrame(True)
        self.cb_interval_function.setObjectName("cb_interval_function")
        self.horizontalLayout_7.addWidget(self.cb_interval_function)
        self.t_interval_function_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_interval_function_desc.setFont(font)
        self.t_interval_function_desc.setWordWrap(True)
        self.t_interval_function_desc.setObjectName("t_interval_function_desc")
        self.horizontalLayout_7.addWidget(self.t_interval_function_desc)
        self.vl_interval_function.addLayout(self.horizontalLayout_7)
        self.t_parameters = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_parameters.sizePolicy().hasHeightForWidth())
        self.t_parameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.t_parameters.setFont(font)
        self.t_parameters.setObjectName("t_parameters")
        self.vl_interval_function.addWidget(self.t_parameters)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.vl_interval_function.addItem(spacerItem7)
        self.gridLayout.addLayout(self.vl_interval_function, 2, 0, 1, 1)
        self.vl_pixel_ordering = QtWidgets.QVBoxLayout()
        self.vl_pixel_ordering.setContentsMargins(2, 2, 2, 2)
        self.vl_pixel_ordering.setObjectName("vl_pixel_ordering")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.t_pixel_ordering = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_pixel_ordering.setFont(font)
        self.t_pixel_ordering.setObjectName("t_pixel_ordering")
        self.horizontalLayout_5.addWidget(self.t_pixel_ordering)
        self.t_pixel_ordering_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering_desc.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_pixel_ordering_desc.setFont(font)
        self.t_pixel_ordering_desc.setWordWrap(True)
        self.t_pixel_ordering_desc.setObjectName("t_pixel_ordering_desc")
        self.horizontalLayout_5.addWidget(self.t_pixel_ordering_desc)
        self.vl_pixel_ordering.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cb_pixel_ordering_option = QtWidgets.QComboBox(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_pixel_ordering_option.sizePolicy().hasHeightForWidth())
        self.cb_pixel_ordering_option.setSizePolicy(sizePolicy)
        self.cb_pixel_ordering_option.setMinimumSize(QtCore.QSize(70, 0))
        self.cb_pixel_ordering_option.setEditable(False)
        self.cb_pixel_ordering_option.setFrame(True)
        self.cb_pixel_ordering_option.setObjectName("cb_pixel_ordering_option")
        self.horizontalLayout_6.addWidget(self.cb_pixel_ordering_option)
        self.t_pixel_ordering_option_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_pixel_ordering_option_desc.sizePolicy().hasHeightForWidth())
        self.t_pixel_ordering_option_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_pixel_ordering_option_desc.setFont(font)
        self.t_pixel_ordering_option_desc.setWordWrap(True)
        self.t_pixel_ordering_option_desc.setObjectName("t_pixel_ordering_option_desc")
        self.horizontalLayout_6.addWidget(self.t_pixel_ordering_option_desc)
        self.vl_pixel_ordering.addLayout(self.horizontalLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_pixel_ordering.addItem(spacerItem8)
        self.gridLayout.addLayout(self.vl_pixel_ordering, 3, 0, 1, 1)
        self.vl_generation = QtWidgets.QVBoxLayout()
        self.vl_generation.setContentsMargins(2, 2, 2, 2)
        self.vl_generation.setObjectName("vl_generation")
        self.hl_generation = QtWidgets.QHBoxLayout()
        self.hl_generation.setObjectName("hl_generation")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_generation.addItem(spacerItem9)
        self.b_generate_preview = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_generate_preview.sizePolicy().hasHeightForWidth())
        self.b_generate_preview.setSizePolicy(sizePolicy)
        self.b_generate_preview.setMinimumSize(QtCore.QSize(100, 30))
        self.b_generate_preview.setObjectName("b_generate_preview")
        self.hl_generation.addWidget(self.b_generate_preview)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_generation.addItem(spacerItem10)
        self.b_generate_full = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_generate_full.sizePolicy().hasHeightForWidth())
        self.b_generate_full.setSizePolicy(sizePolicy)
        self.b_generate_full.setMinimumSize(QtCore.QSize(100, 30))
        self.b_generate_full.setObjectName("b_generate_full")
        self.hl_generation.addWidget(self.b_generate_full)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_generation.addItem(spacerItem11)
        self.vl_generation.addLayout(self.hl_generation)
        self.gridLayout.addLayout(self.vl_generation, 5, 0, 1, 1)
        self.vl_save_location = QtWidgets.QVBoxLayout()
        self.vl_save_location.setContentsMargins(2, 2, 2, 2)
        self.vl_save_location.setObjectName("vl_save_location")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.t_save_location = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location.sizePolicy().hasHeightForWidth())
        self.t_save_location.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.t_save_location.setFont(font)
        self.t_save_location.setObjectName("t_save_location")
        self.horizontalLayout_4.addWidget(self.t_save_location)
        self.t_save_location_desc = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location_desc.sizePolicy().hasHeightForWidth())
        self.t_save_location_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_desc.setFont(font)
        self.t_save_location_desc.setWordWrap(True)
        self.t_save_location_desc.setObjectName("t_save_location_desc")
        self.horizontalLayout_4.addWidget(self.t_save_location_desc)
        self.vl_save_location.addLayout(self.horizontalLayout_4)
        self.hl_save_location = QtWidgets.QHBoxLayout()
        self.hl_save_location.setSpacing(20)
        self.hl_save_location.setObjectName("hl_save_location")
        self.b_save_location = QtWidgets.QPushButton(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save_location.sizePolicy().hasHeightForWidth())
        self.b_save_location.setSizePolicy(sizePolicy)
        self.b_save_location.setMinimumSize(QtCore.QSize(100, 30))
        self.b_save_location.setObjectName("b_save_location")
        self.hl_save_location.addWidget(self.b_save_location)
        self.t_save_location_current = QtWidgets.QLabel(self.scroll_area_settings_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_save_location_current.sizePolicy().hasHeightForWidth())
        self.t_save_location_current.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_save_location_current.setFont(font)
        self.t_save_location_current.setWordWrap(True)
        self.t_save_location_current.setObjectName("t_save_location_current")
        self.hl_save_location.addWidget(self.t_save_location_current)
        self.vl_save_location.addLayout(self.hl_save_location)
        spacerItem12 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.vl_save_location.addItem(spacerItem12)
        self.gridLayout.addLayout(self.vl_save_location, 4, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem13, 6, 0, 1, 1)
        self.scroll_area_settings.setWidget(self.scroll_area_settings_content)
        self.verticalLayout.addWidget(self.scroll_area_settings)
        self.horizontalLayout.addWidget(self.f_settings_panel)
        self.f_preview_panel = QtWidgets.QFrame(self.centralwidget)
        self.f_preview_panel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_preview_panel.sizePolicy().hasHeightForWidth())
        self.f_preview_panel.setSizePolicy(sizePolicy)
        self.f_preview_panel.setAutoFillBackground(False)
        self.f_preview_panel.setFrameShape(QtWidgets.QFrame.Panel)
        self.f_preview_panel.setObjectName("f_preview_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_preview_panel)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl_image_preview = QtWidgets.QHBoxLayout()
        self.hl_image_preview.setObjectName("hl_image_preview")
        self.cb_live_preview = QtWidgets.QCheckBox(self.f_preview_panel)
        self.cb_live_preview.setObjectName("cb_live_preview")
        self.hl_image_preview.addWidget(self.cb_live_preview)
        self.verticalLayout_2.addLayout(self.hl_image_preview)
        self.line_2 = QtWidgets.QFrame(self.f_preview_panel)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.l_generated_image = QtWidgets.QLabel(self.f_preview_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_generated_image.sizePolicy().hasHeightForWidth())
        self.l_generated_image.setSizePolicy(sizePolicy)
        self.l_generated_image.setText("")
        self.l_generated_image.setScaledContents(True)
        self.l_generated_image.setAlignment(QtCore.Qt.AlignCenter)
        self.l_generated_image.setObjectName("l_generated_image")
        self.verticalLayout_2.addWidget(self.l_generated_image)
        spacerItem14 = QtWidgets.QSpacerItem(600, 5, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout.addWidget(self.f_preview_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhi = QtWidgets.QAction(MainWindow)
        self.actionhi.setObjectName("actionhi")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.t_image_mask.setText(QtWidgets.QApplication.translate("MainWindow", "Image Mask", None, -1))
        self.t_image_mask_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Image used for masking parts of the image. Must be black and white.", None, -1))
        self.rb_mask_none.setText(QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.rb_mask_single.setText(QtWidgets.QApplication.translate("MainWindow", "Single Mask", None, -1))
        self.rb_mask_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Mask from Folder", None, -1))
        self.t_no_mask.setText(QtWidgets.QApplication.translate("MainWindow", "No mask image will be used.", None, -1))
        self.b_choose_mask.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Image", None, -1))
        self.l_loaded_mask_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Loaded mask will display here", None, -1))
        self.t_mask_folder_info_header.setText(QtWidgets.QApplication.translate("MainWindow", "Note: If the loaded image is in found in the mask folder it will be ignored.", None, -1))
        self.b_choose_mask_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Folder", None, -1))
        self.t_found_masks.setText(QtWidgets.QApplication.translate("MainWindow", "Found Masks:", None, -1))
        self.t_found_mask_placeholder1.setText(QtWidgets.QApplication.translate("MainWindow", "placeholder1", None, -1))
        self.t_found_mask_placeholder2.setText(QtWidgets.QApplication.translate("MainWindow", "placeholder2", None, -1))
        self.t_image.setText(QtWidgets.QApplication.translate("MainWindow", "Image", None, -1))
        self.t_image_desc.setText(QtWidgets.QApplication.translate("MainWindow", "*Required* This is the image that will have pixel sorting applied to it. JPG, PNG, TIFF, etc.", None, -1))
        self.b_choose_image.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Image", None, -1))
        self.b_load_current.setText(QtWidgets.QApplication.translate("MainWindow", "Load Current", None, -1))
        self.l_loaded_image_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Loaded image will display here", None, -1))
        self.t_interval_sorting.setText(QtWidgets.QApplication.translate("MainWindow", "Interval Sorting", None, -1))
        self.t_interval_sorting_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Controls how the intervals used for sorting are defined.", None, -1))
        self.t_interval_function_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.t_parameters.setText(QtWidgets.QApplication.translate("MainWindow", "Parameters", None, -1))
        self.t_pixel_ordering.setText(QtWidgets.QApplication.translate("MainWindow", "Pixel Ordering", None, -1))
        self.t_pixel_ordering_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Way in which the pixels are ordered.", None, -1))
        self.t_pixel_ordering_option_desc.setText(QtWidgets.QApplication.translate("MainWindow", "(description)", None, -1))
        self.b_generate_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Preview", None, -1))
        self.b_generate_full.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Full", None, -1))
        self.t_save_location.setText(QtWidgets.QApplication.translate("MainWindow", "Save Location", None, -1))
        self.t_save_location_desc.setText(QtWidgets.QApplication.translate("MainWindow", "Choose the location to save the file.", None, -1))
        self.b_save_location.setText(QtWidgets.QApplication.translate("MainWindow", "Save Location", None, -1))
        self.t_save_location_current.setText(QtWidgets.QApplication.translate("MainWindow", "(save location)", None, -1))
        self.cb_live_preview.setText(QtWidgets.QApplication.translate("MainWindow", "Live Preview", None, -1))
        self.actionhi.setText(QtWidgets.QApplication.translate("MainWindow", "hi", None, -1))

