# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\GitHub\pixelsort\pixel_sorter_gui_params.ui',
# licensing of 'f:\GitHub\pixelsort\pixel_sorter_gui_params.ui' applies.
#
# Created: Tue Sep  8 17:43:21 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 550)
        self.f_param_thresh_u = QtWidgets.QFrame(Form)
        self.f_param_thresh_u.setGeometry(QtCore.QRect(200, 226, 398, 87))
        self.f_param_thresh_u.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_thresh_u.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_thresh_u.setObjectName("f_param_thresh_u")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.f_param_thresh_u)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hl_param_thresh_u_t = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_u_t.setSpacing(10)
        self.hl_param_thresh_u_t.setObjectName("hl_param_thresh_u_t")
        self.t_param_thresh_u = QtWidgets.QLabel(self.f_param_thresh_u)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_u.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_u.setSizePolicy(sizePolicy)
        self.t_param_thresh_u.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_u.setObjectName("t_param_thresh_u")
        self.hl_param_thresh_u_t.addWidget(self.t_param_thresh_u)
        self.t_param_thresh_u_desc = QtWidgets.QLabel(self.f_param_thresh_u)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_u_desc.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_u_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_thresh_u_desc.setFont(font)
        self.t_param_thresh_u_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_u_desc.setWordWrap(True)
        self.t_param_thresh_u_desc.setObjectName("t_param_thresh_u_desc")
        self.hl_param_thresh_u_t.addWidget(self.t_param_thresh_u_desc)
        self.verticalLayout_6.addLayout(self.hl_param_thresh_u_t)
        self.hl_param_thresh_u_b = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_u_b.setObjectName("hl_param_thresh_u_b")
        self.t_param_thresh_u_value = QtWidgets.QLabel(self.f_param_thresh_u)
        self.t_param_thresh_u_value.setObjectName("t_param_thresh_u_value")
        self.hl_param_thresh_u_b.addWidget(self.t_param_thresh_u_value)
        self.slider_param_thresh_u = QtWidgets.QSlider(self.f_param_thresh_u)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_thresh_u.sizePolicy().hasHeightForWidth())
        self.slider_param_thresh_u.setSizePolicy(sizePolicy)
        self.slider_param_thresh_u.setMaximum(100)
        self.slider_param_thresh_u.setSingleStep(1)
        self.slider_param_thresh_u.setProperty("value", 0)
        self.slider_param_thresh_u.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_thresh_u.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_thresh_u.setTickInterval(10)
        self.slider_param_thresh_u.setObjectName("slider_param_thresh_u")
        self.hl_param_thresh_u_b.addWidget(self.slider_param_thresh_u)
        self.verticalLayout_6.addLayout(self.hl_param_thresh_u_b)
        self.f_param_clength = QtWidgets.QFrame(Form)
        self.f_param_clength.setGeometry(QtCore.QRect(200, 319, 398, 62))
        self.f_param_clength.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_clength.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_clength.setObjectName("f_param_clength")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.f_param_clength)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.hl_param_clength_t = QtWidgets.QHBoxLayout()
        self.hl_param_clength_t.setSpacing(10)
        self.hl_param_clength_t.setObjectName("hl_param_clength_t")
        self.t_param_clength = QtWidgets.QLabel(self.f_param_clength)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_clength.sizePolicy().hasHeightForWidth())
        self.t_param_clength.setSizePolicy(sizePolicy)
        self.t_param_clength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_clength.setObjectName("t_param_clength")
        self.hl_param_clength_t.addWidget(self.t_param_clength)
        self.t_param_clength_desc = QtWidgets.QLabel(self.f_param_clength)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_clength_desc.sizePolicy().hasHeightForWidth())
        self.t_param_clength_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_clength_desc.setFont(font)
        self.t_param_clength_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_clength_desc.setWordWrap(True)
        self.t_param_clength_desc.setObjectName("t_param_clength_desc")
        self.hl_param_clength_t.addWidget(self.t_param_clength_desc)
        self.verticalLayout_7.addLayout(self.hl_param_clength_t)
        self.hl_param_clength_b = QtWidgets.QHBoxLayout()
        self.hl_param_clength_b.setObjectName("hl_param_clength_b")
        self.t_param_clength_helper = QtWidgets.QLabel(self.f_param_clength)
        self.t_param_clength_helper.setObjectName("t_param_clength_helper")
        self.hl_param_clength_b.addWidget(self.t_param_clength_helper)
        self.tb_param_clength = QtWidgets.QLineEdit(self.f_param_clength)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_param_clength.sizePolicy().hasHeightForWidth())
        self.tb_param_clength.setSizePolicy(sizePolicy)
        self.tb_param_clength.setMinimumSize(QtCore.QSize(20, 0))
        self.tb_param_clength.setMaximumSize(QtCore.QSize(35, 16777215))
        self.tb_param_clength.setText("")
        self.tb_param_clength.setObjectName("tb_param_clength")
        self.hl_param_clength_b.addWidget(self.tb_param_clength)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_param_clength_b.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.hl_param_clength_b)
        self.f_param_angle = QtWidgets.QFrame(Form)
        self.f_param_angle.setGeometry(QtCore.QRect(200, 387, 398, 61))
        self.f_param_angle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_angle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_angle.setObjectName("f_param_angle")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.f_param_angle)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.hl_param_angle_t = QtWidgets.QHBoxLayout()
        self.hl_param_angle_t.setSpacing(10)
        self.hl_param_angle_t.setObjectName("hl_param_angle_t")
        self.t_param_angle = QtWidgets.QLabel(self.f_param_angle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_angle.sizePolicy().hasHeightForWidth())
        self.t_param_angle.setSizePolicy(sizePolicy)
        self.t_param_angle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_angle.setObjectName("t_param_angle")
        self.hl_param_angle_t.addWidget(self.t_param_angle)
        self.t_param_angle_desc = QtWidgets.QLabel(self.f_param_angle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_angle_desc.sizePolicy().hasHeightForWidth())
        self.t_param_angle_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_angle_desc.setFont(font)
        self.t_param_angle_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_angle_desc.setWordWrap(True)
        self.t_param_angle_desc.setObjectName("t_param_angle_desc")
        self.hl_param_angle_t.addWidget(self.t_param_angle_desc)
        self.verticalLayout_8.addLayout(self.hl_param_angle_t)
        self.hl_param_angle_b = QtWidgets.QHBoxLayout()
        self.hl_param_angle_b.setObjectName("hl_param_angle_b")
        self.t_param_angle_value = QtWidgets.QLabel(self.f_param_angle)
        self.t_param_angle_value.setObjectName("t_param_angle_value")
        self.hl_param_angle_b.addWidget(self.t_param_angle_value)
        self.slider_param_angle = QtWidgets.QSlider(self.f_param_angle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_angle.sizePolicy().hasHeightForWidth())
        self.slider_param_angle.setSizePolicy(sizePolicy)
        self.slider_param_angle.setMaximum(360)
        self.slider_param_angle.setSingleStep(1)
        self.slider_param_angle.setProperty("value", 0)
        self.slider_param_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_angle.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_angle.setTickInterval(15)
        self.slider_param_angle.setObjectName("slider_param_angle")
        self.hl_param_angle_b.addWidget(self.slider_param_angle)
        self.verticalLayout_8.addLayout(self.hl_param_angle_b)
        self.f_param_thresh_l = QtWidgets.QFrame(Form)
        self.f_param_thresh_l.setGeometry(QtCore.QRect(200, 133, 398, 87))
        self.f_param_thresh_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_thresh_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_thresh_l.setObjectName("f_param_thresh_l")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.f_param_thresh_l)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hl_param_thresh_l_t = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_l_t.setSpacing(10)
        self.hl_param_thresh_l_t.setObjectName("hl_param_thresh_l_t")
        self.t_param_thresh_l = QtWidgets.QLabel(self.f_param_thresh_l)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_l.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_l.setSizePolicy(sizePolicy)
        self.t_param_thresh_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_l.setObjectName("t_param_thresh_l")
        self.hl_param_thresh_l_t.addWidget(self.t_param_thresh_l)
        self.t_param_thresh_l_desc = QtWidgets.QLabel(self.f_param_thresh_l)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_thresh_l_desc.sizePolicy().hasHeightForWidth())
        self.t_param_thresh_l_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_thresh_l_desc.setFont(font)
        self.t_param_thresh_l_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_thresh_l_desc.setWordWrap(True)
        self.t_param_thresh_l_desc.setObjectName("t_param_thresh_l_desc")
        self.hl_param_thresh_l_t.addWidget(self.t_param_thresh_l_desc)
        self.verticalLayout_5.addLayout(self.hl_param_thresh_l_t)
        self.hl_param_thresh_l_b = QtWidgets.QHBoxLayout()
        self.hl_param_thresh_l_b.setSpacing(6)
        self.hl_param_thresh_l_b.setObjectName("hl_param_thresh_l_b")
        self.t_param_thresh_l_value = QtWidgets.QLabel(self.f_param_thresh_l)
        self.t_param_thresh_l_value.setObjectName("t_param_thresh_l_value")
        self.hl_param_thresh_l_b.addWidget(self.t_param_thresh_l_value)
        self.slider_param_thresh_l = QtWidgets.QSlider(self.f_param_thresh_l)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_thresh_l.sizePolicy().hasHeightForWidth())
        self.slider_param_thresh_l.setSizePolicy(sizePolicy)
        self.slider_param_thresh_l.setMaximum(100)
        self.slider_param_thresh_l.setSingleStep(1)
        self.slider_param_thresh_l.setProperty("value", 0)
        self.slider_param_thresh_l.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_thresh_l.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_thresh_l.setTickInterval(10)
        self.slider_param_thresh_l.setObjectName("slider_param_thresh_l")
        self.hl_param_thresh_l_b.addWidget(self.slider_param_thresh_l)
        self.verticalLayout_5.addLayout(self.hl_param_thresh_l_b)
        self.f_param_random = QtWidgets.QFrame(Form)
        self.f_param_random.setGeometry(QtCore.QRect(200, 60, 398, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_param_random.sizePolicy().hasHeightForWidth())
        self.f_param_random.setSizePolicy(sizePolicy)
        self.f_param_random.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_param_random.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_param_random.setObjectName("f_param_random")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.f_param_random)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hl_param_randomness_t = QtWidgets.QHBoxLayout()
        self.hl_param_randomness_t.setSpacing(10)
        self.hl_param_randomness_t.setObjectName("hl_param_randomness_t")
        self.t_param_randomness = QtWidgets.QLabel(self.f_param_random)
        self.t_param_randomness.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_randomness.setObjectName("t_param_randomness")
        self.hl_param_randomness_t.addWidget(self.t_param_randomness)
        self.t_param_randomness_desc = QtWidgets.QLabel(self.f_param_random)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_randomness_desc.sizePolicy().hasHeightForWidth())
        self.t_param_randomness_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.t_param_randomness_desc.setFont(font)
        self.t_param_randomness_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_param_randomness_desc.setObjectName("t_param_randomness_desc")
        self.hl_param_randomness_t.addWidget(self.t_param_randomness_desc)
        self.verticalLayout_4.addLayout(self.hl_param_randomness_t)
        self.hl_param_randomness_b = QtWidgets.QHBoxLayout()
        self.hl_param_randomness_b.setObjectName("hl_param_randomness_b")
        self.t_param_randomness_value = QtWidgets.QLabel(self.f_param_random)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_param_randomness_value.sizePolicy().hasHeightForWidth())
        self.t_param_randomness_value.setSizePolicy(sizePolicy)
        self.t_param_randomness_value.setObjectName("t_param_randomness_value")
        self.hl_param_randomness_b.addWidget(self.t_param_randomness_value)
        self.slider_param_randomness = QtWidgets.QSlider(self.f_param_random)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_param_randomness.sizePolicy().hasHeightForWidth())
        self.slider_param_randomness.setSizePolicy(sizePolicy)
        self.slider_param_randomness.setMaximum(100)
        self.slider_param_randomness.setProperty("value", 0)
        self.slider_param_randomness.setOrientation(QtCore.Qt.Horizontal)
        self.slider_param_randomness.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_param_randomness.setTickInterval(10)
        self.slider_param_randomness.setObjectName("slider_param_randomness")
        self.hl_param_randomness_b.addWidget(self.slider_param_randomness)
        self.verticalLayout_4.addLayout(self.hl_param_randomness_b)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.t_param_thresh_u.setText(QtWidgets.QApplication.translate("Form", "Threshold (upper)", None, -1))
        self.t_param_thresh_u_desc.setText(QtWidgets.QApplication.translate("Form", "How bright must a pixel be to be considered as a \'border\' for sorting? Takes values from 0-1. 0.8 by default. Used in threshold mode.", None, -1))
        self.t_param_thresh_u_value.setText(QtWidgets.QApplication.translate("Form", "thresh (u) val", None, -1))
        self.t_param_clength.setText(QtWidgets.QApplication.translate("Form", "Char. length", None, -1))
        self.t_param_clength_desc.setText(QtWidgets.QApplication.translate("Form", "Characteristic length for the random width generator. Used in mode random and waves.", None, -1))
        self.t_param_clength_helper.setText(QtWidgets.QApplication.translate("Form", "(0 - inf)", None, -1))
        self.t_param_angle.setText(QtWidgets.QApplication.translate("Form", "Angle", None, -1))
        self.t_param_angle_desc.setText(QtWidgets.QApplication.translate("Form", "Angle at which you\'re pixel sorting in degrees. 0 (horizontal) by default.", None, -1))
        self.t_param_angle_value.setText(QtWidgets.QApplication.translate("Form", "angle val", None, -1))
        self.t_param_thresh_l.setText(QtWidgets.QApplication.translate("Form", "Threshold (lower)", None, -1))
        self.t_param_thresh_l_desc.setText(QtWidgets.QApplication.translate("Form", "How dark must a pixel be to be considered as a \'border\' for sorting? Takes values from 0-1. 0.25 by default. Used in edges and threshold modes.", None, -1))
        self.t_param_thresh_l_value.setText(QtWidgets.QApplication.translate("Form", "thresh (l) val", None, -1))
        self.t_param_randomness.setText(QtWidgets.QApplication.translate("Form", "Randomness", None, -1))
        self.t_param_randomness_desc.setText(QtWidgets.QApplication.translate("Form", "What percentage of intervals not to sort. 0 by default.", None, -1))
        self.t_param_randomness_value.setText(QtWidgets.QApplication.translate("Form", "rand val", None, -1))

